### ISSUE TITLE
Invalid URL 'http://': No host supplied

### ISSUE THREAD

**Issue by anxdpanic** [anxdpanic/plugin.video.youtube#10]
https://github.com/jdf76/plugin.video.youtube/issues/870

**Comment by anxdpanic** [comment]
Should be fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by jmbreuer** [comment]
This started to happen for me last night, only with videos that are / mostly contain music.

See: https://forum.kodi.tv/showthread.php?tid=356934&pid=2983904#pid2983904
and my log: https://paste.kodi.tv/heyiqiyadu.kodi

**Comment by thecosmicslug** [comment]
started to happen yesterday on our Kodi installation, the beta doesn't seem any different. it seems to be only music videos affected.

**Comment by X-dark** [comment]
I can confirm this is still happening with 6.8.7:

```
2020-10-29 13:36:57.175 T:139768501376576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                          
                                            Error Type: <class 'requests.exceptions.InvalidURL'>                
                                            Error Contents: Invalid URL u'http://': No host supplied                                
                                            Traceback (most recent call last):                                                          
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)                                                                
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)                                                       
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)                                                    
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)                                                      
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)                                              
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 768, in on_play
                                                return yt_play.play_video(self, context)                                  
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)                             
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)                                  
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 506, in load_stream_infos
                                                return self._method_get_video_info(video_id)                            
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 892, in _method_get_video_info
                                                license_info.get('url'))                                                                
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1197, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])                  
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/home/xbmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/home/xbmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/xbmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/xbmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/xbmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/xbmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/xbmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2020-10-29 13:36:57.304 T:139771905555136   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=zSvdLcS62ZM]
```

**Comment by ChrisEt** [comment]
I had the same problem today with v6.8.4, mostly with music-related videos.
I updated my plugins, with v6.8.7 the problem doesn't show anymore. :thumbsup: Well done guys!

**Comment by gedreano** [comment]
InvalidURL: Invalid URL u'http://': No host supplied in v6.8.7

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/5538801/kodi.log)

**Comment by LiquidSky** [comment]
Still happening on 6.8.8~beta1:
2020-11-14 11:02:27.504 T:139661432153856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 768, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 911, in _method_get_video_info
                                                license_info.get('url'))
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1216, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2020-11-14 11:02:27.703 T:139664046901632   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=AN2rv6IlSr0]

**Comment by LiquidSky** [comment]
Still happening with 6.8.8~beta1:

`2020-11-14 11:02:27.504 T:139661432153856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 768, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 911, in _method_get_video_info
                                                license_info.get('url'))
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1216, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2020-11-14 11:02:27.703 T:139664046901632   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=AN2rv6IlSr0]
`

**Comment by LiquidSky** [comment]
> test

**Comment by LiquidSky** [comment]
Still happening with 6.8.8~beta1:

[KodiLog.log](https://github.com/anxdpanic/plugin.video.youtube/files/5540480/KodiLog.log)

**Comment by ypcyc** [comment]
Did something change? I've started getting this error today with version 6.8.9
```
021-01-26 20:43:40.853 T:140612565186304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 911, in _method_get_video_info
                                                license_info.get('url'))
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1216, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
```

**Comment by rome2** [comment]
Same here for the last two weeks. I have the same impression that the add on is mostly throwing this error on music related videos. But this doesn't mean that only official music videos or rip offs are affected. Also synthesizer presentations or a video where someone presents an old church organ are throwing this error. Both didn't have anything copyright worthy material in them. The URLs themselves look fine and open without problems in a browser on the same device.

**Comment by ypcyc** [comment]
@rome2
I did this:
Kodi Yotube plugin: * Settings - Maintenance - Delete access_manager.json and then re-login (not re-entering keys)

After that re-login with Google account NOT YouTube account!

**Comment by rome2** [comment]
Thank you very much for your reply. I went through this procedure already a few days ago and now I just tried it again. This makes no difference at all. I only have one account for youtube, google and the API keys so no confusion there.

Just a random link from youtube's suggestions (a classical piece with anonymous music from the 16th century):

https://www.youtube.com/watch?v=9UTe8zQBlT8

The log looks exactly like the one you posted above.

**Comment by criterion9** [comment]
I am also getting this error for some videos. I tried not logged in & logged in but that made no difference. It would seem that somewhere in the stack it is not getting a url to request and ends up passing nothing for the request.

File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 911, in _method_get_video_info
                                                license_info.get('url'))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1216, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied

**Comment by MetalGuardian** [comment]
Also started getting this error today, plugin version: 6.8.9

**Comment by Griff1984** [comment]
Same issue as of 5th Feb (2021). 
However, i managed to make all videos by signing-out. 
As a trial I created a new google account - signed in using the new account, and all videos play.
Have tried logging back in using the original account, and same videos do not play (tried several different devices, and fresh kodi install - same issue when logged in with my original account). 
Not sure why it would work with one account and not another. API keys were the same.

**Comment by GothicChris** [comment]
Same Issue here. For me it did **NOT** work to use another account. Also a re-login didn't worked. 

Any other ideas so far?

System:
Kodi 18.0 - LibreELEC
Raspberry Pi B
**Youtube 6.8.9**

**Comment by rome2** [comment]
Same here. After signing out all videos play fine, logging in again and this error appears. Using a different account or a fresh Kodi installation on a different platform doesn't make a difference.

I've also gone through all the settings in my Youtube and Google accounts but none of the available parameters seems to change anything.

Surprisingly one of the videos that failed previously now works. I've asked the channel owner what she had changed and her answer was that she hadn't touched this video at all after the initial upload.

**Comment by wrapper** [comment]
+1 also getting this issue on music related videos in particular

**Comment by rome2** [comment]
Maybe the location has something to do with it. I'm in Germany and the content production industry is very aggressive around here.

**Comment by thecosmicslug** [comment]
I have been getting this error on mostly music videos also, uk location here

**Comment by anxdpanic** [comment]
Are you all using Kodi 18? I'll generate a test zip or two to see if we can fix/get to the bottom of it.

I stepped away for ~ a month, should hopefully be more active again.

**Comment by criterion9** [comment]
I am on Kodi 18 yes. Thanks for looking into it

**Comment by anxdpanic** [comment]
Can you test and confirm if the issue is resolved in the attached zip. Thanks in advance 👍  [plugin.video.youtube-6.8.9-test1.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5962468/plugin.video.youtube-6.8.9-test1.zip)

**Comment by wanaxe** [comment]
> Can you test and confirm if the issue is resolved in the attached zip. Thanks in advance 👍 [plugin.video.youtube-6.8.9-test1.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5962468/plugin.video.youtube-6.8.9-test1.zip)

Yes, the issue solved. It works for Kodi 18.8 on OSMC. Thank you so much!!!

**Comment by joshg253** [comment]
> 
> 
> > Can you test and confirm if the issue is resolved in the attached zip. Thanks in advance 👍 [plugin.video.youtube-6.8.9-test1.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5962468/plugin.video.youtube-6.8.9-test1.zip)
> 
> Yes, the issue solved. It works for Kodi 18.8 on OSMC. Thank you so much!!!

Fix works for me as well: Kodi 18.9 on Element "Fire TV Edition" (Android).

**Comment by anxdpanic** [comment]
I've updated the development repos and https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev with all the zips. Thanks everyone for testing and confirming.

**Comment by GothicChris** [comment]
> Can you test and confirm if the issue is resolved in the attached zip. Thanks in advance 👍 [plugin.video.youtube-6.8.9-test1.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5962468/plugin.video.youtube-6.8.9-test1.zip)

Thank you. The Fix also works for me on Kodi 18.0 (LibreELEC).

**Comment by Griff1984** [comment]
Fix works on windows 10 Kodi 18.9
Thank you.

**Comment by jmweir** [comment]
Hey @anxdpanic thank you very much for your hard work. I also confirm with your just released version that some videos which did not play for me are now playing.

**Comment by Daidalos117** [comment]
I can confirm that updated version works. Thank you @anxdpanic for your awesome work man!

**Comment by bratekarate** [comment]
I tried the Matrix version. Some videos work, but the majority throws a new error from inputstream.adaptive when using MPD:

```
ERROR <general>: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation.
```

Any Ideas?

**EDIT:** Very weird, I reverted back to the stable release, restarted Kodi and the entire issue with `Invalid URL` disappeared. The aforementioned issue also does not occur anymore.

I will report back if I manage to get the devel zips working with inputstream.adaptive after another restart.

**EDIT2:** All worked fine after a reboot. Ignore my comment.

**Comment by mikromcz** [comment]
I have vener this issue here in the Czech Republic, but yesterday I noticed that music videos can't be played.
same error like here.
with alpha1 version it is working again, thank you.

**Comment by teodoryantcheff** [comment]
Just so my debug info lives here as well -- https://github.com/anxdpanic/plugin.video.youtube/issues/60#issuecomment-779360116

Using 6.8.10-alpha fixed it for me.

**Comment by jleehart** [comment]
> I've updated the development repos and https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev with all the zips. Thanks everyone for testing and confirming.

Thank you very much from Russia

**Comment by ghen2** [comment]
> I've updated the development repos and https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev with all the zips. Thanks everyone for testing and confirming.

6.8.10 alpha1 confirmed playing music videos again on Kodi 18.

**Comment by Sergio-Morello** [comment]
> Можете ли вы проверить и подтвердить, решена ли проблема в прилагаемом zip-архиве. заранее спасибо [plugin.video.youtube-6.8.9-test1.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5962468/plugin.video.youtube-6.8.9-test1.zip)

Good day.
I have the problem described here.
I am trying to install this plugin from a zip file but I get a message that xbmc.pithon ver 2.20.0 was not found.
what am I doing wrong? And how to fix it.
Thank you.

**Comment by Chklang** [comment]
Yes! Thank you for the 6.8.10, the bug is DOWN :)

**Comment by Kunstbanause** [comment]
> > I've updated the development repos and https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev with all the zips. Thanks everyone for testing and confirming.
> 
> 6.8.10 alpha1 confirmed playing music videos again on Kodi 18.

I can confirm music related videos work now for me on raspi 4, libreelec, kodi
