### ISSUE TITLE
Exception in cipher.py

### ISSUE THREAD

**Issue by AlexNk** [anxdpanic/plugin.video.youtube#179]
### Context

* Add-on Version: 6.8.15
* Kodi Version: 18.9.0
* Kodi GUI Language: English
* Operating System: LibreElec

* Video: https://www.youtube.com/watch?v=iiXBwXlYuv8

### Log

```
2021-08-10 13:02:46.354 T:140476929779456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'function(c'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 536, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1092, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1052, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 31, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_javascript, self._javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 75, in _load_javascript
                                                param = int(param)
                                            ValueError: invalid literal for int() with base 10: 'function(c'
                                            -->End of Python script error report<--
```

**Comment by Xenolevis** [comment]
Same issue here, seems to affect music videos. Most other titles play fine.
Add-on version 6.8.15+matrix.1 (unofficial)
LibreElec 19.1.0 nightly on RPI 4

**Comment by GothicChris** [comment]
Same issue here. It doesn't matter which kind of video it is.

Add-On: 6.8.15
LibreElec 9.2.6 (official)
RPI 3 Model B

**Comment by kiorky** [comment]
confirmed

**Comment by vlada-dudr** [comment]
Same here

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v6.8.16

**Comment by AlexNk** [comment]
6.18.16 fixed it for me. Tested it on two different videos that were causing this bug before.

**Comment by vlada-dudr** [comment]
Yes, it seems to work

**Comment by abcnorio** [comment]
Yes - works for me too. Tested on videos that did not work before (search function + firefox plugin to send YT to kodi). Thx!

**Comment by Xenolevis** [comment]
Confirmed working with v6.18.16. Cheers anxdpanic!

**Comment by GothicChris** [comment]
it works

**Comment by kiorky** [comment]
confirmed resolution
