### ISSUE TITLE
Playing video stopped working. Error tracedback to ratebypass.py

### ISSUE THREAD

**Issue by cristianav** [anxdpanic/plugin.video.youtube#185]
```
    Add-on Version: 6.8.16
    Kodi Version: 18.9.0
    Kodi GUI Language: English
    Operating System: LibreELEC 9.2.6
    Hardware: RPi4.arm 4GB
    Operating System Language: English
```

Yesteday I've noticed that out of the sudden, the videos on YT stopped playing, instead throwing the following error in the logs:

```
2021-08-25 22:27:33.176 T:2344829808   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2021-08-25 22:27:33.851 T:2344829808   ERROR: Previous line repeats 1 times.
2021-08-25 22:27:33.851 T:2344829808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'span'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 538, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 966, in _method_get_video_info
                                                self._calculate_n = ratebypass.CalculateN(js)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/ratebypass/ratebypass.py", line 22, in __init__
                                                self.throttling_array = get_throttling_function_array(raw_code)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/ratebypass/ratebypass.py", line 188, in get_throttling_function_array
                                                array_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
                                            AttributeError: 'NoneType' object has no attribute 'span'
                                            -->End of Python script error report<--
2021-08-25 22:27:34.088 T:3011461136   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=DZqNUAk34vc]
```

I don't know if the first error (about HTTPS) has something to do with it. I've been trying to get rid of it by refreshing the API keys, reconnecting the device with google, logout/login and so forth, but with no luck.

What I'm still able to do is to see the subscriptions list, new videos, etc. Only playing is not possible anymore.

As for an workaround fix, I've downgraded the plugin to 6.8.15 and now it seems to be working. Also I've deactivated the auto update functionality to preserve it at that version.

**Comment by oliroe** [comment]
Hi
I'm seeing the exact same issue myself, I can do everything apart from playing a video. Guessing something must have changed at Google's end.
Strangely it works when not using an API Key

**Comment by cristianav** [comment]
Hello,

For me it didn't work without API keys. Downgrading to previous version is the (temporarily I hope) fix for me.

**Comment by anxdpanic** [comment]
Can you guys try out: https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by cristianav** [comment]
@anxdpanic I've just installed the alpha version and I can confirm that the issue seems to be fixed. Thanks!

**Comment by oliroe** [comment]
@anxdpanic managed to get 5mins without my kids watching youtube and it's all fine here as well

Life saver, thanks

**Comment by Wafflestyx** [comment]
@anxdpanic alpha working for me also

**Comment by jmbreuer** [comment]
Ran into this as well - 6.8.17.alpha1+matrix.1 fixes it for me as well.

OT: is there an addon repo that tracks the pre-releases?

**Comment by Rialtho-the-Magnificent** [comment]
so I'm not the only one.. That's reassuring! Now finding out how to apply the (alpha) fix. Normally these updates go by itself S I'm not sure how to apply.

**Comment by anxdpanic** [comment]
@jmbreuer not lately, something I would like to automate more in the near future though so it gets back on track

@Rialtho-the-Magnificent just download the zip and follow https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

**Comment by ErwinBaeyens** [comment]
Same issue here;  installed the patch and it works again. Thanks

**Comment by arfoll** [comment]
After applying the patch the ratebypass issue went away but I got an issue with inputstream (linux), updated that and everything works perfect again.

**Comment by Zynth-dev** [comment]
Confirmed fixed with the new alpha version

**Comment by cooljimy84** [comment]
Was working 9 hours ago here in the UK, now had to install this dev zip. Good catch tho people !

**Comment by gemp** [comment]
Can't install the alpha, it says `The dependency on xbmc.python version 3.0.0 could not be satisfied.` Tho I have (still in Kodi 18.x – cannot upgrade to 19 for compatibility reasons):
```
osmc:~$ python --version
Python 2.7.16
osmc:~$ python3 --version
Python 3.7.3
```

**Comment by anxdpanic** [comment]
@gemp you need to download the zip without `+matrix.1` in the filename

**Comment by gemp** [comment]
@anxdpanic Stupid me... Works again like a charm, a zillion thanks.

**Comment by anxdpanic** [comment]
I submitted the fix to the official repository and waiting for review

**Comment by killerbees19** [comment]
@anxdpanic Thanks! 😊

**Comment by DoWerna** [comment]
thanks!
it works again

**Comment by marcoboutch** [comment]
Thanks!

**Comment by frankrbrts622** [comment]
The 6.8.17.alpha version fixed the problem. I'm using Kodi 18.9 on a mac-Mini. Thanks!!

**Comment by malversan** [comment]
> I submitted the fix to the official repository and waiting for review

Thanks, @anxdpanic . Specially for the fast response.

**Comment by AndiinPanama** [comment]
@anxdpanic 

Great guy! Problem solved. Thank you so much!!!

**Comment by Homi-Bear** [comment]
this fix works for me but only when I turn off inputstreamadaptive (which means no high res youtube)

**Comment by theilenz** [comment]
Alpha version fixed the playback issue, thank you so much.

**Comment by tim942** [comment]
Just wanted to add in that I had to clear the function and data caches out in settings>maintenance to get previously watched videos working again post update.

**Comment by Ranlvor** [comment]
6.8.17 stable update autoinstalled on my kodi, problem is solved.

Thank you.

**Comment by tyctor** [comment]
Hi 
i have an issue with playing youtube videos

lines from log below

this video is not playing at all: 
```
2021-10-14 00:40:46.135 T:1529868480   ERROR: /home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2021-10-14 00:40:46.557 T:1916289984  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=iwgfEQk4p4U
2021-10-14 00:40:46.660 T:1497358528  NOTICE: Creating InputStream
2021-10-14 00:40:46.905 T:1497358528  NOTICE: Creating Demuxer
2021-10-14 00:41:16.957 T:1497358528   ERROR: Open - Error, could not open file https://r1---sn-8vq54voxj1-2gbz.googlevideo.com/videoplayback?expire=1634186445&ei=bWBnYariHM_F1gLWnqCoCQ&ip=89.103.185.57&id=o-AH1zL2ZJQSlDnnG-AuWjNslcgoTOlbdafho5ASTuq1Gk&itag=22&source=youtube&requiressl=yes&mh=2I&mm=31%2C29&mn=sn-8vq54voxj1-2gbz%2Csn-2gb7sn7s&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=573750&vprv=1&mime=video%2Fmp4&ns=LK0TNEF7ppnuNzGFdvxFRxwG&cnr=14&ratebypass=yes&dur=6735.017&lmt=1628154183583384&mt=1634164367&fvip=1&fexp=24001373%2C24007246&beids=9466588&c=WEB&txp=5511222&n=5wa3E6sgBvAEhn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgK34mwxreDxQa558DlNjpC-RfDaM3mILR19JVGL6bb6gCIQDc0b0GP9ncpARloU2y9zzKNaUoQtp8TuaK7CkgGviO_A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIbMvvltz-Oez0GBkLiu5K0H553ncSg1AVu6fQ_UaqyiAiBxVqG7C4gE8B7eC6TvniZR832-Qca450-SP6faaYnnsw%3D%3D
2021-10-14 00:41:16.957 T:1497358528   ERROR: OpenDemuxStream - Error creating demuxer
2021-10-14 00:41:16.957 T:1497358528  NOTICE: CVideoPlayer::OnExit()
2021-10-14 00:41:17.346 T:1916289984  NOTICE: CVideoPlayer::CloseFile()
2021-10-14 00:41:17.346 T:1916289984  NOTICE: VideoPlayer: waiting for threads to exit
2021-10-14 00:41:17.346 T:1916289984  NOTICE: VideoPlayer: finished waiting
```

this video start playing but after few seconds start long buffering
```
2021-10-14 00:54:01.477 T:1529868480   ERROR: /home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2021-10-14 00:54:01.840 T:1916289984  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=9xnjtruSau8
2021-10-14 00:54:02.075 T:1765798080  NOTICE: Creating InputStream
2021-10-14 00:54:03.169 T:1765798080  NOTICE: Creating Demuxer
2021-10-14 00:54:09.541 T:1765798080  NOTICE: Opening stream: 0 source: 256
2021-10-14 00:54:09.542 T:1765798080  NOTICE: Creating video codec with codec id: 27
2021-10-14 00:54:09.555 T:1765798080  NOTICE: Creating video thread
2021-10-14 00:54:09.555 T:1592783040  NOTICE: running thread: video_thread
2021-10-14 00:54:09.582 T:1765798080  NOTICE: Opening stream: 1 source: 256
2021-10-14 00:54:09.582 T:1765798080  NOTICE: Finding audio codec for: 86018
2021-10-14 00:54:09.584 T:1765798080  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2021-10-14 00:54:09.584 T:1765798080  NOTICE: Creating audio thread
2021-10-14 00:54:09.584 T:1404014784  NOTICE: running thread: CVideoPlayerAudio::Process()
2021-10-14 00:54:09.595 T:1404014784  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2021-10-14 00:54:21.195 T:1404014784  NOTICE: CVideoPlayerAudio::Process - stream stalled
2021-10-14 00:54:21.724 T:1592783040 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

for various bitrate (720p, 480) it is same

rPI 3B
OSMC 2020.11
Kodi 18.9
Youtube 6.8.17 (also tryied 6.8.18-alpha)

**Comment by everlanes** [comment]
Same problem here:
```
2021-10-14 09:15:38.400 T:1790935936   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2021-10-14 09:15:39.225 T:1790935936   ERROR: [plugin.video.youtube] Error reason: |accessNotConfigured| with message: |No API keys provided|
2021-10-14 09:15:39.273 T:1937712192  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=Aw0-MxTBj_k
2021-10-14 09:15:39.437 T:1476309888  NOTICE: Creating InputStream
2021-10-14 09:15:39.936 T:1476309888  NOTICE: Creating Demuxer
2021-10-14 09:16:10.051 T:1476309888   ERROR: Open - Error, could not open file https://r2---sn-h0jeened.googlevideo.com/videoplayback?expire=1634217337&ei=GdlnYb6rA4eS1wKG55v4DQ&ip=[IP removed]&id=o-AN0piPsWWFJtZNpub_34wUmnfSAdfoZR3i_tygk3kyux&itag=22&source=youtube&requiressl=yes&mh=ch&mm=31%2C26&mn=sn-h0jeened%2Csn-4g5ednd7&ms=au%2Conr&mv=m&mvi=2&pl=26&initcwndbps=1731250&vprv=1&mime=video%2Fmp4&ns=pnpAQY-LZAmhlX86YrmnLv8G&cnr=14&ratebypass=yes&dur=11222.807&lmt=1551864435541150&mt=1634195333&fvip=2&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=5535432&n=-vwHYKC-7Ls5H0&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgUUsWwLJBJSq7IoIc6jvXJlKse7zXJNvj-HrKHd5vS4kCIBuRhEU_ry4OwcdeyRfaZnzCbZSxCBe3OglL7j89XDAp&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMHRl4FcSrdoURaacQZujOdH1Sa5Cx3b-YlasxdC0hM1AiEA7FYqYVfDZ67oHezXrpYMpx9Qv3-EgFt_1lu5Ubj5Mto%3D
2021-10-14 09:16:10.052 T:1476309888   ERROR: OpenDemuxStream - Error creating demuxer
2021-10-14 09:16:10.052 T:1476309888  NOTICE: CVideoPlayer::OnExit()
2021-10-14 09:16:10.448 T:1937712192  NOTICE: CVideoPlayer::CloseFile()
2021-10-14 09:16:10.449 T:1937712192  NOTICE: VideoPlayer: waiting for threads to exit
2021-10-14 09:16:10.449 T:1937712192  NOTICE: VideoPlayer: finished waiting
```

Opening the given URL in a browser works fine and plays the movie.

**Comment by tyctor** [comment]
> |No API keys provided|

you need to set API keys

**Comment by everlanes** [comment]
> Open - Error, could not open file https:...

Up until yesterday it worked and the link it is complaining about can be opened by a browser without any API key ...
