### ISSUE TITLE
Unable to play any video due to "Unverified HTTPS request is being made to host 'www. youtube.com'"

### ISSUE THREAD

**Issue by alghazanth** [anxdpanic/plugin.video.youtube#191]
### Context

* Add-on Version: 6.8.16+matrix.1
* Kodi Version: 9.1 (19.1.0) Git:20210509-85e05228b4
* Kodi GUI Language: EN
* Operating System: Linux Mint 19 Tara
* Operating System Language: EN

------

### Expected Behavior

Clicking on any video in the plugin interface triggers playback.

------

### Current Behavior

Kodi UI throws error popup, in ~/.kodi/temp/kodi.log I see:

```2021-08-26 22:19:51.642 T:6635     INFO <general>: initializing python engine.
2021-08-26 22:19:52.473 T:6635     INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.16+matrix.1) on Matrix (Kodi-19.1) with Python 3.6.9
                                                        Path: /special/new_uploaded_videos_tv/
                                                        Params: {} 
2021-08-26 22:19:52.558 T:6635     INFO <general>: CPythonInvoker(4, /home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
2021-08-26 22:19:54.089 T:6597    ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Екатерина Шульман.png
2021-08-26 22:19:54.786 T:6635     INFO <general>: initializing python engine.                                                   
2021-08-26 22:19:54.788 T:6635     INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.16+matrix.1) on Matrix (Kodi-19.1) with Python 3.6.9                    
                                                        Path: /play/                     
                                                        Params: {'video_id': 'E4KnrOLue60'}                                       
2021-08-26 22:19:55.614 T:6635    ERROR <general>: /home/invictus/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.
youtube.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                                     InsecureRequestWarning,
                                                                
2021-08-26 22:19:55.712 T:6635    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                       
                                                   Error Type: <class 'AttributeError'> 
                                                   Error Contents: 'NoneType' object has no attribute 'span'
                                                   Traceback (most recent call last):
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                       results = provider.navigate(context)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                       return yt_play.play_video(self, context)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 537, in load_stream_infos
                                                       return self._method_get_video_info(video_id)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 965, in _method_get_video_info
                                                       self._calculate_n = ratebypass.CalculateN(js)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/ratebypass/ratebypass.py", line 22, in __init__
                                                       self.throttling_plan = get_throttling_plan(raw_code)
                                                     File "/home/invictus/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/ratebypass/ratebypass.py", line 257, in get_throttling_plan
                                                       transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
                                                   AttributeError: 'NoneType' object has no attribute 'span'
                                                   -->End of Python script error report<--

2021-08-26 22:19:55.843 T:6635     INFO <general>: Python interpreter stopped
2021-08-26 22:19:55.852 T:6559    ERROR <general>: Skipped 1 duplicate messages..
2021-08-26 22:19:55.852 T:6559    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=E4KnrOLue60]
```

------

### Steps to Reproduce

1. Open addon in Kodi UI
2. Open My subscriptions
3. Click on any video

------

### Log

https://paste.kodi.tv/qopidutide.kodi

------

### Additional Information

I use the plugin with my own Youtube API key.

------

**Comment by alghazanth** [comment]
6.8.17.alpha works as intended, thank you.
