### ISSUE TITLE
does not start on xbox

### ISSUE THREAD

**Issue by serj-47** [anxdpanic/plugin.video.youtube#238]
* Add-on Version:6.8.18+matrix
* Kodi Version:19.3
* Kodi GUI Language:eng
* Operating System:xbox series s
* Operating System Language:eng

Today on my xbox kodi was updated from version 18leia to 19.3matrix and along with this a new youtube addon appeared in the repository.  The youtube install goes fine, but when I try to start it, it just shows youtube error and won't start.  I don't know exactly how to view the logs on the xbox.  * On kodi leia youtube 6.8.18.alfa6 worked fine!

**Comment by MaximumRide707** [comment]
Same issue is happening on my system (Xbox One X). Uninstalled and started fresh, only installing this Add-On. Log below.

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/7445831/kodi.log)

For those that don't want to open log, this is the error:

> 2021-10-29 23:29:57.913 T:1976     INFO <general>: initializing python engine.
2021-10-29 23:29:58.396 T:1976    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'PermissionError'>
                                                   Error Contents: [Errno 13] Permission denied: 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_19.3.0.70_x64__4n2hpmxwrvr6p\\system\\python\\lib\\urllib\\__init__.py'
                                                   Traceback (most recent call last):
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\default.py", line 11, in <module>
                                                       from youtube_plugin.kodion import runner
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\__init__.py", line 18, in <module>
                                                       from .abstract_provider import AbstractProvider
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 14, in <module>
                                                       from six.moves.urllib_parse import quote
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.six\lib\six.py", line 92, in __get__
                                                       result = self._resolve()
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.six\lib\six.py", line 160, in _resolve
                                                       module = _import_module(self.mod)
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.six\lib\six.py", line 82, in _import_module
                                                       __import__(name)
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 715, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 851, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 908, in get_data
                                                   PermissionError: [Errno 13] Permission denied: 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_19.3.0.70_x64__4n2hpmxwrvr6p\\system\\python\\lib\\urllib\\__init__.py'
                                                   -->End of Python script error report<--
                                                   
2021-10-29 23:29:58.409 T:1976     INFO <general>: Python interpreter stopped
