### ISSUE TITLE
KeyError exception

### ISSUE THREAD

**Issue by rusk911** [anxdpanic/plugin.video.youtube#25]
Hi. Getting an exception on new search since yesterday.

`
2020-10-08 07:42:59.624 T:1519891168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'\u043f'
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                result = method(context, re_match)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 247, in _internal_search
                                                self._data_cache.set('search_query', json.dumps({'query': quote(query)}))
                                              File "/usr/lib/python2.7/urllib.py", line 1299, in quote
                                                return ''.join(map(quoter, s))
                                            KeyError: u'\u043f'
                                            -->End of Python script error report<--
2020-10-08 07:42:59.625 T:1519891168   DEBUG: onExecutionDone(15, /home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/default.py)

`

**Comment by tsaklidis** [comment]
Just [created a PR](https://github.com/anxdpanic/plugin.video.youtube/pull/26) about this issue.
The quote has to be encoded
