### ISSUE TITLE
Python 3.9 failure

### ISSUE THREAD

**Issue by asavah** [anxdpanic/plugin.video.youtube#27]
Have Kodi built with python 3.9 on linux.
Open youtube addon.
Navigate to "My Subscriptions", the following exception is produced:
```
2020-10-09 01:03:29.988 T:766      INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.5+matrix.1) on Krypton (Kodi-19.0) with Python 3.9.0
                                                   <--->Path: /
                                                   <--->Params: {}
2020-10-09 01:03:30.270 T:766      INFO <general>: CPythonInvoker(2, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
2020-10-09 01:03:31.338 T:766      INFO <general>: initializing python engine.
2020-10-09 01:03:31.339 T:766      INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.5+matrix.1) on Krypton (Kodi-19.0) with Python 3.9.0
                                                   <--->Path: /special/new_uploaded_videos_tv/
                                                   <--->Params: {}
2020-10-09 01:03:32.873 T:766     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'html.parser' has no attribute 'HTMLParseError'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/video_item.py", line 117, in set_plot
                                                       plot = html_parser.HTMLParser().unescape(plot)
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   During handling of the above exception, another exception occurred:
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                       results = provider.navigate(context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 797, in _on_yt_specials
                                                       return yt_specials.process(category, self, context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 346, in process
                                                       return _process_new_uploaded_videos_tv(provider, context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 313, in _process_new_uploaded_videos_tv
                                                       result.extend(tv.my_subscriptions_to_items(provider, context, json_data))
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tv.py", line 56, in my_subscriptions_to_items
                                                       utils.update_video_infos(provider, context, video_id_dict, channel_items_dict=channel_item_dict, use_play_data=use_play_data)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 338, in update_video_infos
                                                       video_item.set_plot(description)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/video_item.py", line 118, in set_plot
                                                       except html_parser.HTMLParseError as _:
                                                   AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
                                                   -->End of Python script error report<--
2020-10-09 01:03:32.894 T:766      INFO <general>: Python interpreter stopped
2020-10-09 01:03:32.894 T:766      INFO <general>: Python interpreter stopped
2020-10-09 01:03:32.906 T:768     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/
2020-10-09 01:03:32.916 T:571     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos_tv/) failed
```

Reportedly in python 3.9 html.parser.HTMLParser().unescape() function was removed, it was undocumented and deprecated since python 3.4 . https://bugs.python.org/issue37328

And HTMLParseError was dropped in python 3.5 https://github.com/python/cpython/commit/73a4359eb0eb624c588c5d52083ea4944f9787ea#diff-1a7486df8279dbac7f20abd487947845

There are several instances of html_parser.HTMLParser().unescape used mostly in kodion/*_item.py .
I've fixed this locally for me, but sadly I'm not able to submit a proper PR as writing code that works for both 2.7 and 3.x is not my cup of tea :(

**Comment by asavah** [comment]
A link for my quick and dirty fix in case someone else might need it https://gist.github.com/asavah/772c5e806b825b10492d21d01c7e3c58#file-yt-3-9-patch

**Comment by anxdpanic** [comment]
Thanks @asavah 

Can you give https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev a try, just to double check. Thanks!

**Comment by asavah** [comment]
Thanks, that was fast :)
Quick runtime testing shows that everything is fine with python 3.9, updated and restarted kodi to make sure that the service is restarted with new code, navigation and playback is fine, no errors.
Thanks again for your awesome work.

**Comment by anxdpanic** [comment]
Thank you for confirming :)
