### ISSUE TITLE
Empty "My Subscriptions"

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#280]
* Add-on Version: 6.8.18
* Kodi Version: Kodi 18.9
* Kodi GUI Language: English
* Operating System: CoreELEC
* Operating System Language: English

------

### Current Behavior

Clicking `My Subscriptions` shows empty. Many users on [Kodi forums](https://forum.kodi.tv/showthread.php?tid=356934&pid=3088660#pid3088660) are reporting same behavior. Videos themself play.

------
Additionally I cleared all cache and created new API key. Under these new installation conditions now `Subscriptions` no longer displays anything as well. Videos themselves play.

------
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click on `My Subscriptions`
2. Screen will be empty

**Comment by netty0** [comment]
Also experiencing this issue. Any word from @anxdpanic 
Thank you

**Comment by chapperino** [comment]
Can also confirm this issue has existed for 12 hours now. Addon is basically unusable now unfortunately 

On Kodi 18. I even refreshed with new API keys & same problem

**Comment by dtteufel** [comment]
No issues here.
Vero 4K - OSMC 19.3 - plugin.video.youtube-6.8.18+matrix.1.zip
Running fine. if a little slow to display 'My Subscriptions.
Consider the possibility that this is related to issues with Servers hosted in Eastern Europe - at least one Enigma2 support server appears to have been compromised in the last week.

**Comment by fragande** [comment]
My list isn't empty, but it seems I only get videos from two or three channels at a time (subscribed to about 150). Seemingly on random, it can be completely different channels each refresh.

**Comment by chapperino** [comment]
> My list isn't empty, but it seems I only get videos from two or three channels at a time (subscribed to about 150). Seemingly on random, it can be completely different channels each refresh.

Yes, I also experience that. The issue changes from not showing anything at all to only showing 1 channel   


Maybe problem is only affecting people who subscribe to a lot of channels?

**Comment by neo-neo1** [comment]
> My list isn't empty, but it seems I only get videos from two or three channels at a time (subscribed to about 150). Seemingly on random, it can be completely different channels each refresh.

Yes same issue I’m experiencing also.

**Comment by pery69** [comment]
The same issue, my subscriptions are not diplayed. Kodi 19.3.Opensuse.

**Comment by Wafflestyx** [comment]
Had this issue last night, this morning all my subscriptions displayed normally. Tried about 10min ago and nothing displayed. 

Guess YouTube is messing with the api again?

**Comment by bmh67wa** [comment]
This also started happening to me a couple of days ago. Sometimes random videos will show up in the list but more often than not nothing at all shows up. Tried a new API key as suggested in the Kodi forums with the same result. LibreELEC Kodi 19.3 Raspberry Pi 4.

**Comment by JohnMostlyR** [comment]
I also can confirm the issue is back. I firtst noticed it on the 27th at around 4.30 CET. First the list was lonly occupied with some channels, from US only? Then after clicking 'My Subscriptions' again the list stayed empty.
Now, it goes on and off, clicking 'My Subscriptions' repeatedly will show an empty list, or the complete list or with channels missing, just now I was missing only the US channels.
It helps though to keep on refreshing.

**Comment by netty0** [comment]
Please mark this Addon as broken in the Official Kodi Repo to attract dev attention. Its functionally broken unfortunately.

**Comment by neo-neo1** [comment]
> Please mark this Addon as broken in the Official Kodi Repo to attract dev attention. Its functionally broken unfortunately.

I agree. Wish I could help

**Comment by anxdpanic** [comment]
Okay, so the solution to the issue is to mark the add-on broken and effectively stop the add-on from working completely for everyone...  because I didn't have time to reply to an issue that no one has even provided a debug log for?

iirc this has happened to that api area before and resolved itself. But I will try to take a look.

**Comment by anxdpanic** [comment]
Just confirmed here that it is working as expected on my end. So about those debug logs...

**Comment by JohnMostlyR** [comment]
> Just confirmed here that it is working as expected on my end. So about those debug logs...

For over a day I don't experience the issue anymore. Next time I'll try to provide you the logs, sorry for that :-)

**Comment by mikromcz** [comment]
> My list isn't empty, but it seems I only get videos from two or three channels at a time (subscribed to about 150). Seemingly on random, it can be completely different channels each refresh.

That is exactly my issue for the last couple of weeks. Like only 70% of new videos are shown in My Subscriptions. And the rest never show, or might randomly show in few days.
So now I have to check manually on the phone, and save missing/interesting videos to Watch Later an play them from there in Kodi.

**Comment by GekoCH** [comment]
I have the same problem. It shows no videos at all in the My Supscription menu. This is a small part of the log file:

```

2022-05-28 22:44:51.899 T:29669   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UCgYkuL87rUwiBl7tqfN53Eg (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 829, in fetch_xml
                                                       _response = requests.get(_url, {}, headers=headers, verify=self._verify, allow_redirects=True)
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 76, in get
                                                       return request('get', url, params=params, **kwargs)
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>: requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UCgYkuL87rUwiBl7tqfN53Eg (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
                                                   
2022-05-28 22:44:51.899 T:29669   ERROR <general>: 
2022-05-28 22:44:51.899 T:29669   ERROR <general>: [plugin.video.youtube] Failed |None|
2022-05-28 22:44:51.900 T:29569   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 411, in connect
                                                       self.sock = ssl_wrap_socket(
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UCxBheRQeJNTBYAsPAHhaBhA (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 829, in fetch_xml
                                                       _response = requests.get(_url, {}, headers=headers, verify=self._verify, allow_redirects=True)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 76, in get
                                                       return request('get', url, params=params, **kwargs)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UCxBheRQeJNTBYAsPAHhaBhA (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
                                                   
2022-05-28 22:44:51.900 T:29569   ERROR <general>: 
2022-05-28 22:44:51.900 T:29569   ERROR <general>: [plugin.video.youtube] Failed |None|
2022-05-28 22:44:51.901 T:29633   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 411, in connect
                                                       self.sock = ssl_wrap_socket(
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UC7he88s5y9vM3VlRriggs7A (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: Traceback (most recent call last):
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 829, in fetch_xml
                                                       _response = requests.get(_url, {}, headers=headers, verify=self._verify, allow_redirects=True)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 76, in get
                                                       return request('get', url, params=params, **kwargs)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /feeds/videos.xml?channel_id=UC7he88s5y9vM3VlRriggs7A (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
                                                   
2022-05-28 22:44:51.901 T:29633   ERROR <general>: 
2022-05-28 22:44:51.901 T:29633   ERROR <general>: [plugin.video.youtube] Failed |None|
2022-05-28 22:44:52.785 T:28916    INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.18+matrix.1) on N***** (Kodi-20.0) with Python 3.9.12
                                                   	Path: /
                                                   	Params: {}
2022-05-28 22:44:52.792 T:28916 WARNING <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.

```

**Comment by cas--** [comment]
In my case I am subscribed to  65 channels and was seeing the SSLError in logs. The issue is due to creating too many connections to Youtube when fetching more than ~40 channel feeds. 

This particular code does not use API calls so that is not part of the issue. Instead fetches the public videos.xml feeds for each channel. Perhaps there is a bug in library code when needing to verify the SSL cert but should really be limiting the number of connecting when fetching this data. 

The temporary workaround for those with SSLError in logs (I assume everyone affected here) is to turn off SSL verification in settings:

![screen01](https://user-images.githubusercontent.com/606038/236828158-589002ae-653a-4ec6-8820-4a867313f520.jpg)

I will provide a PR later but this is the code that should actually resolve the issue:

```diff
--- resources/lib/youtube_plugin/youtube/client/youtube.py
+++ resources/lib/youtube_plugin/youtube/client/youtube.py
@@ -821,11 +821,17 @@ class YouTube(LoginClient):
                     'Accept-Language': 'en-US,en;q=0.7,de;q=0.3'
                 }
 
+                requests_session = requests.Session()
+                requests_session.headers = headers
+                requests_session.verify = self._verify
+                adapter = requests.adapters.HTTPAdapter(pool_maxsize=5, pool_block=True)
+                requests_session.mount("https://", adapter)
+
                 responses = []
 
                 def fetch_xml(_url, _responses):
                     try:
-                        _response = requests.get(_url, {}, headers=headers, verify=self._verify, allow_redirects=True)
+                        _response = requests_session.get(_url)
                     except:
                         _response = None
                         _context.log_error('Failed |%s|' % traceback.print_exc())
```
