### ISSUE TITLE
6.8.21 - exception on exiting the addon

### ISSUE THREAD

**Issue by asavah** [anxdpanic/plugin.video.youtube#367]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.21
* Kodi Version: (20.0-BETA1 (19.90.801) Git:20221128-692da7507b). Platform: Linux x86 64-bit
* Kodi GUI Language: english
* Operating System: own project, GNU/linux, gbm
* Operating System Language: en_GB

------

### Expected Behavior

Please describe the behavior you are expecting.

Clean exit after exiting the addon by using "backspace" key

------

### Current Behavior

What is the current behavior?
A wild exception occurs:
```
2022-12-03 17:27:40.941 T:1784736    info <general>: [plugin.video.youtube] Running: YouTube (6.8.21+matrix.1) on N***** (Kodi-20.0) with Python 3.11.0
                                                   <--->Path: /
                                                   <--->Params: {}
2022-12-03 17:27:40.956 T:1784736   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: cannot start a transaction within a transaction
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 34, in run
                                                       results = provider.navigate(context)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 124, in navigate
                                                       result = method(context, re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 157, in _internal_root
                                                       return self.on_root(context, re_match)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1697, in on_root
                                                       if settings.get_bool('youtube.folder.tags.show', True) and (len(tags.get_channels('')) > 0):
                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tags.py", line 66, in get_channels
                                                       cur.execute("begin")
                                                   sqlite3.OperationalError: cannot start a transaction within a transaction
                                                   -->End of Python script error report<--
...................................................
2022-12-03 17:27:41.000 T:1784866   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2022-12-03 17:27:41.003 T:1784684   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start the addon
2. Exit the addon by using "backspace" key.
3. Observe error pop-up

Sometimes it exits cleanly, however the next time you enter the addon - it fails.
Backtrace is the same in both cases.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/wegelumone.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by anxdpanic** [comment]
can you try disabling Settings - Folder - Subscription Groups

I'll revert the tags pr soon though, (the cause)

**Comment by toupeira** [comment]
Disabling Subscription Groups got rid of the crashes here on 6.8.22 :+1:

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/pull/373
next alpha should be resolved

**Comment by anxdpanic** [comment]
6.8.23 pushed to repos, and submitted
