### ISSUE TITLE
ValueError (6.8.7)

### ISSUE THREAD

**Issue by Rudd-O** [anxdpanic/plugin.video.youtube#42]
```
2020-10-31 10:22:35.713 T:139694146844416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Extra data: line 20 column 5 - line 21 column 2 (char 1128 - 1131)
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 12, in <module>
                                                from youtube_plugin import youtube
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/__init__.py", line 11, in <module>
                                                from .provider import Provider
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 22, in <module>
                                                from ..youtube.client import YouTube
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__init__.py", line 11, in <module>
                                                from .youtube import YouTube
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 19, in <module>
                                                from .login_client import LoginClient
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/login_client.py", line 17, in <module>
                                                from .__config__ import api, youtube_tv, developer_keys, keys_changed
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__config__.py", line 222, in <module>
                                                _api_check = APICheck(__context, __settings)
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__config__.py", line 30, in __init__
                                                self._am_jstore = LoginTokenStore()
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/login_tokens.py", line 17, in __init__
                                                JSONStore.__init__(self, 'access_manager.json')
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/json_store.py", line 39, in __init__
                                                self.load()
                                              File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/json_store.py", line 59, in load
                                                data = json.load(jsonfile)
                                              File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
                                                **kw)
                                              File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib64/python2.7/json/decoder.py", line 367, in decode
                                                raise ValueError(errmsg("Extra data", s, end, len(s)))
                                            ValueError: Extra data: line 20 column 5 - line 21 column 2 (char 1128 - 1131)
                                            -->End of Python script error report<--
2020-10-31 10:22:35.757 T:139693308282624   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
```

That's weird.  This was not happening 4 days ago.

**Comment by anxdpanic** [comment]
You can either delete `access_manager.json` using Settings - Maintenance (will require relogin), or you can edit the `access_manager.json` file in your addon_data folder to fix the corrupt file. likely a missing `}`

**Comment by Rudd-O** [comment]
OK.  Thank you.

**Comment by Rudd-O** [comment]
it worked
