### ISSUE TITLE
Plugin fails to load playlists if they contain a deleted video with "Hide SHort Videos" is enabled

### ISSUE THREAD

**Issue by ryanwalder** [anxdpanic/plugin.video.youtube#438]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.1
* Kodi GUI Language: English
* Operating System: Ubuntu 22.04
* Operating System Language: English

------

### Expected Behaviour

Load Playlists without error

------

### Current Behaviour

If you have a playlist with a deleted video in and the "Hide Shorts" option enabled the plugin fails to get the video length which causes the playlist to not display.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Youtube:

1. Create Youtube Playlist
2. Add videos to playlist
3. Delete video from youtube (unlisting may also work, not tested)

Kodi:

1. Enable/Load Plugin
2. Enable "Hide Short videos" option
3. Load playlist
4. Plugin Throws Error

------

### Log

```
2023-03-28 00:29:06.732 T:1482322    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.1) with Python 3.8.10
                                                   	Path: /channel/mine/playlist/PLR47uZg6xyIPrMtCdx9oIpSN0RzfNaGwO/
                                                   	Params: {}
2023-03-28 00:29:43.244 T:1482322    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.1) with Python 3.8.10
                                                   	Path: /channel/mine/playlist/PLR47uZg6xyIPrMtCdx9oIpSN0RzfNaGwO/
                                                   	Params: {'page': '2', 'page_token': 'EAAaBlBUOkNESQ'}
2023-03-28 00:29:43.701 T:1482322   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '<' not supported between instances of 'int' and 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 35, in run
                                                       results = provider.navigate(context)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 475, in _on_channel_playlist
                                                       result.extend(v3.response_to_items(self, context, json_data))
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 301, in response_to_items
                                                       result = utils.filter_short_videos(context, result)
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 685, in filter_short_videos
                                                       if hasattr(item, '_duration') and (0 < item.get_duration() <= 60):
                                                   TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

------

### Additional Information

Given the error it looks like it's failing because it can't get the video length so can't check it's length is under 60 seconds. I would assume this also happens with other times the plugin can't get the length of a video.

**Comment by ryanwalder** [comment]
Closing, just seen the fix in master.
