### ISSUE TITLE
Error with some playlists when setting 'Hide short videos' is enabled

### ISSUE THREAD

**Issue by MusterGit** [anxdpanic/plugin.video.youtube#440]
### Context

* Add-on Version: 7.0.1
* Kodi Version: 20.1 (Nexus)
* Kodi GUI Language:
* Operating System: LibreELEC nightly-20230401
* Operating System Language:

------

### Expected Behavior

1. Select a channel
2. Select Playlists
3. Select a playlist
4. See list of videos

------

### Current Behavior

1. Select a channel
2. Select Playlists
3. Select a playlist
5. Sometimes list of videos, sometimes error

------

### Steps to Reproduce

1. Enable setting 'Hide short videos'
2. Open channel 'Schattennaseweis' (UCOmJzJatrm9u_1enp1GlUpw)
3. Open playlists
6. Open playlist 'Was wollen wir trinken?' (PL5dLUYzBHyvgTE_UR9G6hpoFLcy8QNqjR)

------

### Log

```
2023-04-03 22:08:02.797 T:22293    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.1) with Python 3.11.2
                                                   	Path: /channel/UCOmJzJatrm9u_1enp1GlUpw/playlist/PL5dLUYzBHyvgTE_UR9G6hpoFLcy8QNqjR/
                                                   	Params: {}
2023-04-03 22:08:03.619 T:22293   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '<' not supported between instances of 'int' and 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 35, in run
                                                       results = provider.navigate(context)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                       result = method(context, re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 475, in _on_channel_playlist
                                                       result.extend(v3.response_to_items(self, context, json_data))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 301, in response_to_items
                                                       result = utils.filter_short_videos(context, result)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 685, in filter_short_videos
                                                       if hasattr(item, '_duration') and item.get_duration() and (0 < item.get_duration() <= 60):
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '<' not supported between instances of 'int' and 'NoneType'
                                                   -->End of Python script error report<--
```

------

### Additional Information

I guess `hasattr(item, '_duration')` is a workaround for a missing `is_playable` function.
The _duration field is initialized with None and apparently not set yet. `get_duration` then just returns this field's value and thus a comparison of 0 and None triggers the exception.

Well, as a workaround I replaced line 685 of resources/lib/youtube_plugin/youtube/helper/utils.py with:
`            if hasattr(item, '_duration') and item.get_duration() and (0 < item.get_duration() <= 60):
`

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/7.x.x-dev fixed
