### ISSUE TITLE
Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by Hasky23** [anxdpanic/plugin.video.youtube#482]
### Context

Some videos are not playable with a message indicated bellow. It seems that YouTube plugin implementation is based on **embed** feature.

* Add-on Version: 7.0.1 (altered to go around Issue #442)
* Kodi Version: 20.0.0
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: US English 

------

### Expected Behavior

It is desirable to be able to play some videos which was restricted to be played on YouTube  website only. The message is indicated bellow.

It seems like YouTube add-on is based on **embed** feature of the service, the same message reproduced through "**Share->embed**" option.

------

### Current Behavior

YouTube add-on in Kodi produces following message

Video unavailable
Playback on other websites has been disabled by the video owner
[Watch on YouTube](http://www.youtube.com/watch?v=s5qx1X78ujE)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. in a web browser add a video **s5qx1X78ujE** in **Liked Videos** playlist
2. in Kodi launch YouTube add-on
3. try to play the video from **Liked Videos** section

Same message can be reproduced in web browser:

1. load any YouTube video in a browser
2. substitute video ID with **s5qx1X78ujE**
3.  use '**Share->embed**' feature
4. read the message

------

### Log

2023-05-10 14:53:37.545 T:11520    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.0) with Python 3.8.15
                                                   	Path: /
                                                   	Params: {}
2023-05-10 14:53:42.004 T:11520    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.0) with Python 3.8.15
                                                   	Path: /channel/mine/playlist/LL/
                                                   	Params: {}
2023-05-10 14:53:45.517 T:11520    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.0) with Python 3.8.15
                                                   	Path: /play/
                                                   	Params: {'video_id': 's5qx1X78ujE'}
2023-05-10 14:53:46.172 T:11520   error <general>: Traceback (most recent call last):
                                                   
2023-05-10 14:53:46.172 T:11520   error <general>: 
2023-05-10 14:53:46.172 T:11520   error <general>:   File "C:\bin\Users\Kodi_20\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                   
2023-05-10 14:53:46.172 T:11520   error <general>: 
2023-05-10 14:53:46.172 T:11520   error <general>:   File "C:\bin\Users\Kodi_20\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 101, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                   
2023-05-10 14:53:46.172 T:11520   error <general>: 
2023-05-10 14:53:46.172 T:11520   error <general>:   File "C:\bin\Users\Kodi_20\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 542, in load_stream_infos
                                                       return self._method_get_video_info(video_id)
                                                   
2023-05-10 14:53:46.172 T:11520   error <general>: 
2023-05-10 14:53:46.172 T:11520   error <general>:   File "C:\bin\Users\Kodi_20\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 886, in _method_get_video_info
                                                       raise YouTubeException(reason)
                                                   
2023-05-10 14:53:46.172 T:11520   error <general>: 
2023-05-10 14:53:46.172 T:11520   error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: Playback on other websites has been disabled by the video owner
                                                   
2023-05-10 14:53:46.172 T:11520   error <general>: 
2023-05-10 14:53:46.172 T:11520   error <general>: [plugin.video.youtube] None
2023-05-10 14:53:46.189 T:14096   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=s5qx1X78ujE]

------

### Additional Information

Inside Chrome web browser the video can be played successfully. Perhaps there is a way around this issue by making YouTube website 'to believe' that add-on is run in a web browser? 

------

**Comment by MoojMidge** [comment]
If you have altered the plugin to use the embedded client then this is expected.

Use the dev release instead:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/7.x.x-dev

**Comment by MoojMidge** [comment]
Closed by #506
