### ISSUE TITLE
Error on getting watch later list

### ISSUE THREAD

**Issue by MuertiMuertman** [anxdpanic/plugin.video.youtube#494]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.1
* Kodi GUI Language: english
* Operating System: osmc
* Operating System Language: english

------

### Expected Behavior

getting the watch later list

------

### Current Behavior

I followed this guide on getting the playlist id: [https://github.com/anxdpanic/plugin.video.youtube/issues/69#issuecomment-766843932](url)

however when trying to open the list I get the following error (playlist id replaced with PL_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX):

  
```
2023-06-23 10:39:07.236 T:3048     info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.1) with Python 3.9.2
                                                   	  Path: /
                                                   	  Params: {}
  2023-06-23 10:39:10.590 T:3048     info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.1) with Python 3.9.2
                                                   	  Path: /channel/mine/playlist/PL_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/
                                                   	  Params: {}
  2023-06-23 10:39:11.235 T:3048    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                     Error Type: <class 'TypeError'>
                                                     Error Contents: '<' not supported between instances of 'int' and 'NoneType'
                                                     Traceback (most recent call last):
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                         runner.run(__provider__)
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                         __RUNNER__.run(provider, context)
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 35, in run
                                                         results = provider.navigate(context)
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                         result = method(context, re_match)
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                         return func(*args, **kwargs)
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 475, in _on_channel_playlist
                                                         result.extend(v3.response_to_items(self, context, json_data))
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 301, in response_to_items
                                                         result = utils.filter_short_videos(context, result)
                                                       File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 685, in filter_short_videos
                                                         if hasattr(item, '_duration') and (0 < item.get_duration() <= 60):
                                                     TypeError: '<' not supported between instances of 'int' and 'NoneType'
                                                     -->End of Python script error report<--
                                                     
  2023-06-23 10:39:11.434 T:3053    error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/channel/mine/playlist/PL_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/
  2023-06-23 10:39:11.445 T:2828    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/channel/mine/playlist/PL_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/) failed
```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. restart system
2. open youtube add-on
3. try to open "watch later"

**Comment by anxdpanic** [comment]
Report if the issue is still ongoing.
