### ISSUE TITLE
7.0.2.1 broken on Kodi

### ISSUE THREAD

**Issue by develroo** [anxdpanic/plugin.video.youtube#517]
Just upgraded to v7.0.21 Now this happens. 
```

2023-09-17 18:11:52.066 T:17278   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name '__li__' is not defined
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 14, in <module>
                                                       from infotagger.listitem import ListItemInfoTag
                                                   ModuleNotFoundError: No module named 'infotagger'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 11, in <module>
                                                       from youtube_plugin.kodion import runner
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 21, in <module>
                                                       from .impl import Context
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/__init__.py", line 12, in <module>
                                                       from .xbmc.xbmc_context import XbmcContext as Context
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context.py", line 29, in <module>
                                                       from .xbmc_playlist import XbmcPlaylist
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_playlist.py", line 15, in <module>
                                                       from . import xbmc_items
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 16, in <module>
                                                       class ListItemInfoTag:
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 17, in ListItemInfoTag
                                                       __slots__ = (__li__, )
                                                   NameError: name '__li__' is not defined
                                                   -->End of Python script error report<--

```

Thoughts?

**Comment by MoojMidge** [comment]
I'm guessing you are using v7.0.2.1 on Kodi 19? Are you using the official or the unofficial release?

The Matrix release hasn't been tested and this bug slipped in.

Should be fixed by [plugin.video.youtube-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-7.0.2.2.matrix.1.zip) (official) / [plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip) (unofficial)

It would be good if you can test this and confirm, then I can push out a quick fix.

Next time please also try to follow the issue template as best you can. It saves time not having to guess things.

**Comment by develroo** [comment]
The official plugin.`plugin.video.youtube-7.0.2.1.matrix.1.zip`

I am using OSMC yes.. which is based on `Kodi (20.2). Platform: Linux ARM 32-bit (version for Vero)`.

Downgrading to the previous version fixed the issue though, so currently `plugin.video.youtube v7.0.1` is working. 

Hope that helps.

**Comment by develroo** [comment]
Frak so I just realised I made an ass of myself, I instinctively  clicked on the latest asset release without thinking about the version of Kodi. 

I will try the correct version and test. If no bugs then I will close this issue as the  embarrassment it is. Doh!

**Comment by develroo** [comment]
Yeah.. seems to work as before. My bad. Sorry for the noise. 

Thanks for your work. Love this addon!

**Comment by filippobistaffa** [comment]
> I'm guessing you are using v7.0.2.1 on Kodi 19? Are you using the official or the unofficial release?
> 
> The Matrix release hasn't been tested and this bug slipped in.
> 
> Should be fixed by [plugin.video.youtube-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-7.0.2.2.matrix.1.zip) (official) / [plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip) (unofficial)
> 
> It would be good if you can test this and confirm, then I can push out a quick fix.
> 
> Next time please also try to follow the issue template as best you can. It saves time not having to guess things.

Can you explain a bit better? I'm using this version (7.0.2.2-unofficial) and now I get this error:
```
2023-09-18 13:30:47.452 T:13802   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: ListItemInfoTag.__init__() got an unexpected keyword argument 'tag_type'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                       results = provider.navigate(context)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                       result = method(context, re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 770, in on_play
                                                       return yt_play.play_video(self, context)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 101, in play_video
                                                       item = to_playback_item(context, video_item)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 240, in to_playback_item
                                                       return to_play_item(context, base_item)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 49, in to_play_item
                                                       info_tag = ListItemInfoTag(list_item, tag_type='video')
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: ListItemInfoTag.__init__() got an unexpected keyword argument 'tag_type'
                                                   -->End of Python script error report<--
```

**Comment by MoojMidge** [comment]
@develroo - It's all good. Glad it is working, the official Nexus version is the only one that I had the opportunity to actually test/use.


@filippobistaffa - Are you sure you are using `7.0.2.2-unofficial`? Do you mean `unofficial-7.0.2.2`? That is for Kodi Nexus or newer (Kodi 20+).

The error in the log snippet should only occur when using `unofficial-7.0.2.2.matrix.1` for Kodi Matrix (Kodi 19).

It is a bit difficult to explain better when I don't even know what version of Kodi or which version of the plugin you are using. Help me help you by providing some basic information.

If you are using Kodi Matrix (Kodi 19) try redownloading and testing again - [plugin.video.youtube-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-7.0.2.2.matrix.1.zip) (official) / [plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip) (unofficial)

**Comment by filippobistaffa** [comment]
@MoojMidge sorry for the confusion. I'm using Kodi 20.2.0 and I tried installing [plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-unofficial-7.0.2.2.matrix.1.zip).

**Comment by MoojMidge** [comment]
@filippobistaffa - Thanks for clearing that up, that explains things now. Seems to be the same root cause as @develroo where you are using the Kodi 19 (Matrix) version of the plugin with Kodi 20 (Nexus).

No apology is necessary, just a bit of info goes a long way. Regardless of the incorrect version being used, the fact that you both took the time to provide feedback helped identify a couple of bugs that needed to be fixed.

Neither of these issues actually effect the version of the plugin for Kodi 20, so you should just use one of the following instead of the Kodi 19 (Matrix) versions:
- [plugin.video.youtube-7.0.2.1.zip](https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.0.2.1/plugin.video.youtube-7.0.2.1.zip) (official)
- [plugin.video.youtube-unofficial-7.0.2.2.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-unofficial-7.0.2.2.zip) (unofficial)

**Comment by filippobistaffa** [comment]
Ah! Now I get the "matrix" in the filename! Thanks for explaining :) I got it working now.

**Comment by MurDocgz** [comment]
I can confirm that plugin.video.youtube-7.0.2.2.matrix.1 works well for me on matrix 19.5,
Just 2 issues, autoplay recommended video still doesn't work and related videos always comes up empty,
plugin.video.youtube-7.0.2.1.matrix.1 came up with a YouTube error message the second I installed it and would not open at all,

**Comment by MoojMidge** [comment]
@MurDocgz - thanks for testing and providing feedback. [v7.0.2.2](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.2.2) has now been released. 

The issue with recommended and related videos is due to a Youtube API change, but requires some time to fix. Refer #508 for details
