### ISSUE TITLE
errors all the time: NameError: name 'constants' is not defined

### ISSUE THREAD

**Issue by damnms** [anxdpanic/plugin.video.youtube#518]
### Context

I just updated to the latest version because the videos are only shown in low quality, thought an update may fix that.
now i get all the time errors, but video playback seem to work

* Add-on Version: 7.0.2.1
* Kodi Version: 20.2
* Kodi GUI Language: german
* Operating System: coreelec latest
* Operating System Language: german

------

### Expected Behavior

no error messages and playback of fullhd videos

------

### Current Behavior

error messages in the gui

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. not sure, just updated from some rc7 or so to latest stable
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

```
2023-09-17 18:54:44.092 T:3867     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.1) on N***** (Kodi-20.2) with Python 3.11.2
                                                   	Path: /
                                                   	Params: {}
2023-09-17 18:54:44.123 T:3867    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'constants' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 72, in run
                                                       if context.get_settings().is_override_view_enabled():
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/abstract_settings.py", line 94, in is_override_view_enabled
                                                       return self.get_bool(constants.setting.VIEW_OVERRIDE, False)
                                                                            ^^^^^^^^^
                                                   NameError: name 'constants' is not defined
                                                   -->End of Python script error report<--

```

------

### Additional Information

------

**Comment by ducarpit** [comment]
Me too, same error :(

**Comment by MoojMidge** [comment]
The unofficial version hasn't been tested and this bug slipped in.

Should be fixed by [plugin.video.youtube-unofficial-7.0.2.2.zip](https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.2.2/plugin.video.youtube-unofficial-7.0.2.2.zip)

It would be good if you can test this and confirm, then I can push out a quick fix.

**Comment by damnms** [comment]
thanks, i will test that.
short question: whats the difference between "unofficial" and "official"? :P 
thought unofficial sounds like "no age restrictions implemented" or so
would maybe a nice thing to add that to the README?

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/wiki/FAQ#difference-between-the-official-and-unofficial-versions

**Comment by damnms** [comment]
can confirm the newest version works, thanks!
