### ISSUE TITLE
Videos wont play 7.0.2.2 Memory Leak

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#525]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2 20+ Official
* Kodi Version: 20.2
* Kodi GUI Language: English
* Operating System: OSMC 2023-8-1
* Operating System Language: English

------

### Expected Behavior
Videos Play

------

### Current Behavior

Video Do not play, gets "One or more items failed to play, check log for more information" error

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install 7.0.2.2 20+ Official
2. Play video
3. Video doesnt plat and gives "One or more items failed to play, check log for more information" error
4. Logs show this exception

"EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: _get() got an unexpected keyword argument 'language_name'"
------

### Log

2023-10-20 03:33:01.090 T:764     debug <general>: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
2023-10-20 03:33:01.110 T:765     debug <general>: Thread ScriptObs start, auto delete: false
2023-10-20 03:33:01.227 T:764     debug <general>: -->Python Interpreter Initialized<--
2023-10-20 03:33:01.227 T:764     debug <general>: 
                                                   
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12): full python path:
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):   custom python path:
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.certifi/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.chardet/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.idna/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.infotagger/resources/modules
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.inputstreamhelper/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.requests/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /home/osmc/.kodi/addons/script.module.urllib3/lib
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):   default python path:
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /usr/lib/python39.zip
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /usr/lib/python3.9
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /usr/lib/python3.9/lib-dynload
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /usr/local/lib/python3.9/dist-packages
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):     /usr/lib/python3/dist-packages
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12): adding args:
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):  plugin://plugin.video.youtube/play/
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):  3
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):  ?video_id=drqFwPuTezs
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12):  resume:false
2023-10-20 03:33:01.227 T:764     debug <general>: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib
2023-10-20 03:33:01.228 T:764     debug <general>: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 3.0.1 of the xbmc.python api
2023-10-20 03:33:01.310 T:526     debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-10-20 03:33:02.659 T:526     debug <general>: ------ Window Deinit (DialogNotification.xml) ------
2023-10-20 03:33:03.243 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2023-10-20 03:33:03.243 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2023-10-20 03:33:03.243 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2023-10-20 03:33:03.243 T:764     debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2023-10-20 03:33:03.244 T:764     debug <general>: [plugin.video.youtube] send_notification: |check_settings| -> |{"use_httpd": true, "httpd_port": 50152, "whitelist": "", "httpd_address": "0.0.0.0"}|
2023-10-20 03:33:03.248 T:764     debug <general>: [plugin.video.youtube] JSONStore Load |b'/home/osmc/.kodi/userdata/addon_data/plugin.video.youtube/api_keys.json'|
2023-10-20 03:33:03.249 T:764     debug <general>: [plugin.video.youtube] JSONStore Load |b'/home/osmc/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json'|
2023-10-20 03:33:03.250 T:764     debug <general>: [plugin.video.youtube] User: |0| Using API key set: |own|
2023-10-20 03:33:03.266 T:575     debug <general>: [plugin.video.youtube] onNotification: |check_settings| -> |{"use_httpd": true, "httpd_port": 50152, "whitelist": "", "httpd_address": "0.0.0.0"}|
2023-10-20 03:33:03.277 T:764     debug <general>: [plugin.video.youtube] Starting Kodion framework by bromix...
2023-10-20 03:33:03.277 T:764      info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.2) with Python 3.9.2
                                                   	Path: /play/
                                                   	Params: {'video_id': 'drqFwPuTezs'}
2023-10-20 03:33:03.285 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2023-10-20 03:33:03.285 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2023-10-20 03:33:03.285 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2023-10-20 03:33:03.285 T:764     debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2023-10-20 03:33:03.301 T:764     debug <general>: [plugin.video.youtube] JSONStore Load |b'/home/osmc/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json'|
2023-10-20 03:33:03.302 T:764     debug <general>: [plugin.video.youtube] Selecting YouTube config "All"
2023-10-20 03:33:03.302 T:764     debug <general>: [plugin.video.youtube] Access token count: |2| Refresh token count: |2|
2023-10-20 03:33:03.310 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2023-10-20 03:33:03.310 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2023-10-20 03:33:03.310 T:764     debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2023-10-20 03:33:03.310 T:764     debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2023-10-20 03:33:03.311 T:764     debug <general>: [plugin.video.youtube] User is logged in
2023-10-20 03:33:03.522 T:764     debug <general>: [plugin.video.youtube] Retrieved video info for video_id: drqFwPuTezs, using ANDROID client (logged in)
2023-10-20 03:33:03.523 T:764     debug <general>: [plugin.video.youtube] Subtitle get_subtitles: for setting |1|
2023-10-20 03:33:03.534 T:526     debug <general>: ------ Window Init (DialogSelect.xml) ------
2023-10-20 03:33:04.665 T:560     debug <general>: CLibInputKeyboard::ProcessKey - using delay: 750ms repeat: 80ms
2023-10-20 03:33:04.665 T:766     debug <general>: Thread Timer start, auto delete: false
2023-10-20 03:33:04.672 T:526     debug <general>: Keyboard: scancode: 0x1c, sym: 0x0d, unicode: 0x0d, modifier: 0x0
2023-10-20 03:33:04.672 T:526     debug <general>: HandleKey: return (0xf00d) pressed, window 12000, action is Select
2023-10-20 03:33:04.745 T:766     debug <general>: Thread Timer 3687837952 terminating
2023-10-20 03:33:04.755 T:526     debug <general>: Keyboard: scancode: 0x1c, sym: 0x0d, unicode: 0x0d, modifier: 0x0
2023-10-20 03:33:05.081 T:526     debug <general>: ------ Window Deinit (DialogSelect.xml) ------
2023-10-20 03:33:05.100 T:764     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: _get() got an unexpected keyword argument 'language_name'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                       results = provider.navigate(context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 770, in on_play
                                                       return yt_play.play_video(self, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 102, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 883, in load_stream_infos
                                                       return self._get_video_info()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1439, in _get_video_info
                                                       captions = captions.get_subtitles()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 146, in get_subtitles
                                                       return self._prompt()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 171, in _prompt
                                                       return self._get(language=languages[choice][0], language_name=languages[choice][1])
                                                   TypeError: _get() got an unexpected keyword argument 'language_name'
                                                   -->End of Python script error report<--
                                                   
2023-10-20 03:33:05.100 T:764     debug <general>: onExecutionDone(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py)
2023-10-20 03:33:05.104 T:526     debug <general>: ------ Window Init (DialogNotification.xml) ------
2023-10-20 03:33:05.130 T:764     debug <general>: .
2023-10-20 03:33:05.244 T:764     debug <general>: Python interpreter stopped
2023-10-20 03:33:05.245 T:764     debug <general>: Thread LanguageInvoker 3655930112 terminating
2023-10-20 03:33:05.252 T:765     debug <general>: Thread ScriptObs 3751780608 terminating
2023-10-20 03:33:05.255 T:526     debug <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-10-20 03:33:05.255 T:526     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=drqFwPuTezs]
2023-10-20 03:33:05.255 T:526     debug <general>: Playlist Player: no more playable items... aborting playback
2023-10-20 03:33:05.256 T:767     debug <general>: Thread BackgroundLoader start, auto delete: false
2023-10-20 03:33:05.269 T:767     debug <general>: Thread BackgroundLoader 3664322816 terminating
2023-10-20 03:33:05.318 T:575     debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2023-10-20 03:33:05.318 T:575     debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2023-10-20 03:33:05.318 T:575     debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2023-10-20 03:33:05.318 T:575     debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2023-10-20 03:33:05.334 T:647     debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2023-10-20 03:33:05.334 T:647     debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2023-10-20 03:33:05.334 T:647     debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2023-10-20 03:33:05.334 T:647     debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2023-10-20 03:33:05.345 T:647     debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2023-10-20 03:33:05.345 T:647     debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2023-10-20 03:33:05.345 T:647     debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2023-10-20 03:33:05.346 T:647     debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2023-10-20 03:33:06.187 T:560     debug <general>: CLibInputKeyboard::ProcessKey - using delay: 750ms repeat: 80ms
2023-10-20 03:33:06.187 T:768     debug <general>: Thread Timer start, auto delete: false
2023-10-20 03:33:06.199 T:526     debug <general>: Keyboard: scancode: 0x9e, sym: 0xa6, unicode: 0x00, modifier: 0x0
2023-10-20 03:33:06.235 T:768     debug <general>: Thread Timer 3687837952 terminating
2023-10-20 03:33:06.241 T:526     debug <general>: Keyboard: scancode: 0x9e, sym: 0xa6, unicode: 0x00, modifier: 0x0
2023-10-20 03:33:06.241 T:526     debug <general>: HandleKey: browser_back (0xf0b0) pressed, window 10025, action is Back
2023-10-20 03:33:06.241 T:526     debug <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/)

------

**Comment by MoojMidge** [comment]
That error message is overly dramatic, the problem is just a typo and fixed by https://github.com/MoojMidge/plugin.video.youtube/commit/b9296e699ad0cf21c2e69d2afdf777e11b273e8a

In the meantime, until the fix is released, you can make the same changes yourself, or simply configure the subtitle language selection in the plugin settings to a fixed language, rather than asking for the language every time.

**Comment by ghost** [comment]
I dont know if the one or more videos failed to play was related, I seemed to fix it reinstalling the app. I wouldnt be surprised if theres memory leaks though as the current release does appear to have freezing issues sometimes when I keep playing videos long enough

**Comment by MoojMidge** [comment]
> I dont know if the one or more videos failed to play was related, I seemed to fix it reinstalling the app.

Not really related. The cause has already been identified as indicated previously, and a fix will be available in the next release. Re-installing the plugin has probably just reset the setting I advised you to change as a workaround.


> I wouldnt be surprised if theres memory leaks though as the current release does appear to have freezing issues sometimes when I keep playing videos long enough

I suppose it is possible, but not because of this issue. Someone else mentioned a similar issue with videos freezing after 40-45 minutes, but didn't provide a log, so it is just about impossible to figure out what the problem may be.

Generally speaking though, an actual memory leak would have more significant effects than the video simply freezing.

If you can, it would be good if you can follow the instructions [here](https://kodi.wiki/view/Log_file/Advanced) to add the following to your advanced settings file. This will enable debug logging in the background without anything being visible to you when using Kodi.
```
<advancedsettings>
    <loglevel>1</loglevel>  
</advancedsettings>
```

If you see the freezing occur again, then you can post your debug log and hopefully it will provide some details of what the problem may be.

**Comment by ghost** [comment]
created a new issue it may be related too

https://github.com/anxdpanic/plugin.video.youtube/issues/533

**Comment by MoojMidge** [comment]
Please don't open up additional issues without providing any additional details. It is unlikely that there is a memory leak, and the plugin does not actually handle the playback of the video.

If you do have a log and think there is an problem with the plugin, feel free to open an issue, but the problems you are describing are relatively common general video playback issues that should be raised with the OSMC team.

**Comment by ghost** [comment]
I added a log (although very long due to waiting over an hour for it to take effect and not wanting to guess where to cut it off) to issue [#533](https://github.com/anxdpanic/plugin.video.youtube/issues/533) If you want you can check to see if you find issues with your plugin in there.

**Comment by MoojMidge** [comment]
That is a completely different issue.

This particular issue is about the subtitle language selection dialog not working, lets keep it on-topic and not mix things up.

**Comment by MoojMidge** [comment]
Duplicate of #534

**Comment by MoojMidge** [comment]
I'm going to close this as it is a bit muddled up already and there is a better description of the problem in #534 

Don't wan't to dismiss your questions regarding freezing/crashing, but this is just not the correct place to trying to resolve those problems.
