### ISSUE TITLE
My Subscriptions: TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by probonopd** [anxdpanic/plugin.video.youtube#555]
### Context

Please provide any relevant information about your setup

* Add-on Version: YouTube (7.0.3+beta.1) on Nexus (Kodi-20.2) with Python 3.11.2 from `plugin.video.youtube-7.0.3+beta.1.zip`
* Kodi Version: YouTube (7.0.3+beta.1) on Nexus (Kodi-20.2) with Python 3.11.2
* Kodi GUI Language: en
* Operating System: LibreELEC
* Operating System Language: en

------

### Expected Behavior

"My Subscriptions" works

------

### Current Behavior

When trying to access "My Subscriptions":

```
2024-01-16 19:34:19.640 T:16271    info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.1) on Nexus (Kodi-20.2) with Python 3.11.2
                                                   Path: /special/new_uploaded_videos_tv/
                                                   Params: {'category_label': '[B]My Subscriptions[/B]'}
2024-01-16 19:34:19.711 T:16271   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: string indices must be integers, not 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 17, in <module>
                                                       runner.run(__provider__)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_runner.py", line 59, in run
                                                       results = provider.navigate(context)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 116, in navigate
                                                       result = method(context, re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 675, in _on_yt_specials
                                                       return yt_specials.process(category, self, context)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 327, in process
                                                       return _process_new_uploaded_videos_tv(provider, context)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 304, in _process_new_uploaded_videos_tv
                                                       return tv.my_subscriptions_to_items(provider,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tv.py", line 37, in my_subscriptions_to_items
                                                       channel = item['channel'].lower()
                                                                 ~~~~^^^^^^^^^^^
                                                   TypeError: string indices must be integers, not 'str'
                                                   -->End of Python script error report<--

2024-01-16 19:34:19.963 T:16270   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/?category_label=%5bB%5dMy%20Subscriptions%5b%2fB%5d
2024-01-16 19:34:19.979 T:683     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos_tv/?category_label=%5bB%5dMy%20Subscriptions%5b%2fB%5d) failed
```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install YouTube (7.0.3+beta.1) on Nexus (Kodi-20.2) with Python 3.11.2 from `plugin.video.youtube-7.0.3+beta.1.zip`
2. Go through the google.com/account authorization 2x (why is this needed after an update?)
3.  Try to access "My Subscriptions"

------

### Log

Please see above.

**Comment by MoojMidge** [comment]
Try to clear your data cache and try again.  `Settings > Maintenance > Clear data cache`

**Comment by upbox-org** [comment]
> Try to clear your data cache and try again. `Settings > Maintenance > Clear data cache`

Clearing the cache fixed it for me.

**Comment by MoojMidge** [comment]
Something I forgot to update with the change in data storage format. It will happen again whenever you login, but the fix is simple: https://github.com/MoojMidge/plugin.video.youtube/commit/acd6e5327f7400d83fc7ee8e52bc47d4a43b3a77

**Comment by misslisa62tx** [comment]
That doesn't fix it for me.  The GUI says I successfully cleared the cache, but the error persists.

**Comment by MoojMidge** [comment]
Only two possibilities really:

1. You didnt clear the data cache. There is the cache and there is the data cache. You need to clear the data cache. Try it again.
2. You logged out and logged back in. Unless you applied the actual fix (https://github.com/MoojMidge/plugin.video.youtube/commit/acd6e5327f7400d83fc7ee8e52bc47d4a43b3a77) yourself, you need to clear the data cache every time you login.

**Comment by misslisa62tx** [comment]
I didn't know I needed to log out.  Applied the fix and that resolved the issue.  

I appreciate the help, thanks.

**Comment by probonopd** [comment]
Thanks for fixing ths.

Out of curiosity: Is there a way to go from an old version of the plugin to the latest one without having to do the annoying 2x Google login dance again? (If not, what is the technical reason?) Stuff like that makes this plugin less than ideal for "set it up and forget" scenarios like non-tech-savvy friends and family.

**Comment by MoojMidge** [comment]
Did you have to logon again when updating to v7.0.3+beta.2?

> Out of curiosity: Is there a way to go from an old version of the plugin to the latest one without having to do the annoying 2x Google login dance again?

If you are only talking about having to logon when updating from a version before v7.0.3+beta.1, then yes it is possible, but doesn't currently.

> what is the technical reason?

Basically [this](https://github.com/anxdpanic/plugin.video.youtube/commit/e9ba8112cee43635dce495aab466c77a6743e3d2) was removed as part of changes to try and reuse common code, which in turn was part of an effort to prevent issues with the JSON data getting corrupted and completely preventing the plugin from running.

> Stuff like that makes this plugin less than ideal for "set it up and forget" scenarios like non-tech-savvy friends and family.

Sure, but this is a beta version, released specifically because it needs testing. Not everything can be done at once.
