### ISSUE TITLE
Player response failed for video_id: vid_id, using android client (logged in)

### ISSUE THREAD

**Issue by NuxRo** [anxdpanic/plugin.video.youtube#582]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2 (with my own api key, obviously)
* Kodi Version: 20.4
* Kodi GUI Language: English
* Operating System: Android (Firestick 4k Max)
* Operating System Language: English

------

### Expected Behavior

Videos should start playing when "clicked" on

------

### Current Behavior

"My subscriptions" page is showing all the video, but starting one fails with the error:
`Player response failed for video_id: $vid_id, using android client (logged in)`

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start Kodi
2. Go to Addons/Youtube/My Subscriptions
3. Start a video

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

2024-02-17 23:32:41.922 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:32:41.965 T:6831     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.4) with Python 3.11.2
                                                   	Path: /
                                                   	Params: {}
2024-02-17 23:32:41.976 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:32:41.977 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:32:41.994 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:32:41.996 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:32:43.709 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 43
2024-02-17 23:32:44.363 T:6831     info <general>: Skipped 3 duplicate messages..
2024-02-17 23:32:44.363 T:6831     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.4) with Python 3.11.2
                                                   	Path: /special/new_uploaded_videos_tv/
                                                   	Params: {}
2024-02-17 23:32:44.375 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:32:44.376 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:32:44.403 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:32:44.404 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:32:49.050 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 43
2024-02-17 23:32:50.918 T:6831     info <general>: Skipped 3 duplicate messages..
2024-02-17 23:32:50.918 T:6831     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.4) with Python 3.11.2
                                                   	Path: /play/
                                                   	Params: {'video_id': 'Xi-FfaU84KY'}
2024-02-17 23:32:50.929 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:32:50.931 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:32:51.125 T:6831    error <general>: [plugin.video.youtube] Player response failed for video_id: Xi-FfaU84KY, using android client (logged in)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-17 23:32:51.135 T:6831    error <general>: Traceback (most recent call last):
                                                   
2024-02-17 23:32:51.135 T:6831    error <general>: 
2024-02-17 23:32:51.136 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                   
2024-02-17 23:32:51.137 T:6831    error <general>: 
2024-02-17 23:32:51.137 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   
2024-02-17 23:32:51.137 T:6831    error <general>: 
2024-02-17 23:32:51.137 T:6831    error <general>: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-17 23:32:51.137 T:6831    error <general>: 
2024-02-17 23:32:51.137 T:6831    error <general>: 
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   
2024-02-17 23:32:51.137 T:6831    error <general>: 
2024-02-17 23:32:51.137 T:6831    error <general>: Traceback (most recent call last):
                                                   
2024-02-17 23:32:51.137 T:6831    error <general>: 
2024-02-17 23:32:51.139 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:32:51.139 T:6831    error <general>: 
2024-02-17 23:32:51.139 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 102, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:32:51.140 T:6831    error <general>: 
2024-02-17 23:32:51.140 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 883, in load_stream_infos
                                                       return self._get_video_info()
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:32:51.140 T:6831    error <general>: 
2024-02-17 23:32:51.140 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1323, in _get_video_info
                                                       result = self._request(
                                                                ^^^^^^^^^^^^^^
                                                   
2024-02-17 23:32:51.140 T:6831    error <general>: 
2024-02-17 23:32:51.140 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 937, in _request
                                                       raise YouTubeException(error_msg) from error
                                                   
2024-02-17 23:32:51.140 T:6831    error <general>: 
2024-02-17 23:32:51.140 T:6831    error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: Player response failed for video_id: Xi-FfaU84KY, using android client (logged in)
                                                   
2024-02-17 23:32:51.141 T:6831    error <general>: 
2024-02-17 23:32:51.141 T:6831    error <general>: [plugin.video.youtube] None
2024-02-17 23:32:51.160 T:6657    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=Xi-FfaU84KY]
2024-02-17 23:33:00.434 T:6657     info <general>: NFS is idle. Closing the remaining connections.
2024-02-17 23:33:01.124 T:6760     info <general>: PVR Manager: Starting cleanup of cached images.
2024-02-17 23:33:02.801 T:6760     info <general>: PVR Manager: Cleaned up 0 cached images.
2024-02-17 23:33:03.747 T:6753     info <general>: JSONRPC Server: New connection added
2024-02-17 23:33:06.611 T:6753     info <general>: JSONRPC Server: Disconnection detected
2024-02-17 23:35:58.335 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 43
2024-02-17 23:37:48.668 T:6624     info <general>: Skipped 3 duplicate messages..
2024-02-17 23:37:48.668 T:6624  warning <general>: CPeripheralBusAndroid: failed to remove input device with ID 43 because it couldn't be found
2024-02-17 23:42:15.234 T:6624     info <general>: CAndroidUtils: Current resolution: 1920x1080 1920x1080 @ 60.000004 - Full Screen
2024-02-17 23:42:15.240 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:42:15.245 T:6624  warning <general>: CPeripheralBusAndroid: failed to update input device with ID 5 because it couldn't be found
2024-02-17 23:42:15.246 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:42:26.103 T:6656     info <general>: Skipped 6 duplicate messages..
2024-02-17 23:42:26.103 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:42:26.313 T:6831     info <general>: Skipped 1 duplicate messages..
2024-02-17 23:42:26.313 T:6831     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.4) with Python 3.11.2
                                                   	Path: /play/
                                                   	Params: {'video_id': 'wHengimtTR4'}
2024-02-17 23:42:26.327 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:42:26.329 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:42:26.681 T:6831    error <general>: [plugin.video.youtube] Player response failed for video_id: wHengimtTR4, using android client (logged in)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-17 23:42:26.685 T:6831    error <general>: Traceback (most recent call last):
                                                   
2024-02-17 23:42:26.685 T:6831    error <general>: 
2024-02-17 23:42:26.686 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                   
2024-02-17 23:42:26.686 T:6831    error <general>: 
2024-02-17 23:42:26.686 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   
2024-02-17 23:42:26.686 T:6831    error <general>: 
2024-02-17 23:42:26.686 T:6831    error <general>: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-17 23:42:26.686 T:6831    error <general>: 
2024-02-17 23:42:26.686 T:6831    error <general>: 
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   
2024-02-17 23:42:26.686 T:6831    error <general>: 
2024-02-17 23:42:26.686 T:6831    error <general>: Traceback (most recent call last):
                                                   
2024-02-17 23:42:26.686 T:6831    error <general>: 
2024-02-17 23:42:26.688 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:42:26.689 T:6831    error <general>: 
2024-02-17 23:42:26.689 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 102, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:42:26.689 T:6831    error <general>: 
2024-02-17 23:42:26.690 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 883, in load_stream_infos
                                                       return self._get_video_info()
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:42:26.690 T:6831    error <general>: 
2024-02-17 23:42:26.690 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1323, in _get_video_info
                                                       result = self._request(
                                                                ^^^^^^^^^^^^^^
                                                   
2024-02-17 23:42:26.690 T:6831    error <general>: 
2024-02-17 23:42:26.690 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 937, in _request
                                                       raise YouTubeException(error_msg) from error
                                                   
2024-02-17 23:42:26.690 T:6831    error <general>: 
2024-02-17 23:42:26.690 T:6831    error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: Player response failed for video_id: wHengimtTR4, using android client (logged in)
                                                   
2024-02-17 23:42:26.690 T:6831    error <general>: 
2024-02-17 23:42:26.690 T:6831    error <general>: [plugin.video.youtube] None
2024-02-17 23:42:26.706 T:6657    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=wHengimtTR4]
2024-02-17 23:42:26.706 T:6657     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-02-17 23:42:27.979 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:42:39.198 T:6656     info <general>: Skipped 11 duplicate messages..
2024-02-17 23:42:39.198 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:42:40.770 T:6657     info <general>: Skipped 7 duplicate messages..
2024-02-17 23:42:40.769 T:6657     info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2024-02-17 23:42:43.401 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:42:45.057 T:6657     info <general>: Skipped 7 duplicate messages..
2024-02-17 23:42:45.057 T:6657     info <general>: Loading skin file: EventLog.xml, load type: KEEP_IN_MEMORY
2024-02-17 23:42:49.761 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:43:00.640 T:6656     info <general>: Skipped 11 duplicate messages..
2024-02-17 23:43:00.640 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:43:10.978 T:6656     info <general>: Skipped 11 duplicate messages..
2024-02-17 23:43:10.978 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:43:12.735 T:6657     info <general>: Skipped 5 duplicate messages..
2024-02-17 23:43:12.735 T:6657     info <general>: Loading skin file: SettingsCategory.xml, load type: KEEP_IN_MEMORY
2024-02-17 23:43:14.560 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:47:55.199 T:6656     info <general>: Skipped 17 duplicate messages..
2024-02-17 23:47:55.199 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:47:56.839 T:6657     info <general>: Skipped 7 duplicate messages..
2024-02-17 23:47:56.839 T:6657     info <general>: Loading skin file: SettingsSystemInfo.xml, load type: KEEP_IN_MEMORY
2024-02-17 23:48:02.329 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:48:13.778 T:6656     info <general>: Skipped 9 duplicate messages..
2024-02-17 23:48:13.778 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:48:23.997 T:6656     info <general>: Skipped 17 duplicate messages..
2024-02-17 23:48:23.997 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:48:31.538 T:6657     info <general>: Skipped 23 duplicate messages..
2024-02-17 23:48:31.537 T:6657     info <general>: Log level changed to "trace"
2024-02-17 23:48:31.538 T:6657     info <general>: Enabled debug logging due to GUI setting. Level 2.
2024-02-17 23:50:00.075 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:50:07.440 T:6657     info <general>: Skipped 15 duplicate messages..
2024-02-17 23:50:07.440 T:6657    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-02-17 23:50:08.550 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:50:08.658 T:6831     info <general>: Skipped 1 duplicate messages..
2024-02-17 23:50:08.658 T:6831     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.4) with Python 3.11.2
                                                   	Path: /special/new_uploaded_videos_tv/
                                                   	Params: {}
2024-02-17 23:50:08.669 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:50:08.671 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:50:10.128 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:50:20.890 T:6656     info <general>: Skipped 13 duplicate messages..
2024-02-17 23:50:20.890 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:50:37.008 T:6656     info <general>: Skipped 9 duplicate messages..
2024-02-17 23:50:37.008 T:6656  warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 44
2024-02-17 23:50:37.083 T:6831     info <general>: Skipped 1 duplicate messages..
2024-02-17 23:50:37.083 T:6831     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.4) with Python 3.11.2
                                                   	Path: /play/
                                                   	Params: {'video_id': 'wHengimtTR4'}
2024-02-17 23:50:37.094 T:6831  warning <CSettingsManager>: unable to read value of setting "kodion.mpd.quality.selection"
2024-02-17 23:50:37.096 T:6831  warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2024-02-17 23:50:37.387 T:6831    error <general>: [plugin.video.youtube] Player response failed for video_id: wHengimtTR4, using android client (logged in)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-17 23:50:37.391 T:6831    error <general>: Traceback (most recent call last):
                                                   
2024-02-17 23:50:37.391 T:6831    error <general>: 
2024-02-17 23:50:37.392 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                   
2024-02-17 23:50:37.393 T:6831    error <general>: 
2024-02-17 23:50:37.393 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   
2024-02-17 23:50:37.393 T:6831    error <general>: 
2024-02-17 23:50:37.393 T:6831    error <general>: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-17 23:50:37.393 T:6831    error <general>: 
2024-02-17 23:50:37.394 T:6831    error <general>: 
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   
2024-02-17 23:50:37.394 T:6831    error <general>: 
2024-02-17 23:50:37.394 T:6831    error <general>: Traceback (most recent call last):
                                                   
2024-02-17 23:50:37.394 T:6831    error <general>: 
2024-02-17 23:50:37.396 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:50:37.396 T:6831    error <general>: 
2024-02-17 23:50:37.396 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 102, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:50:37.398 T:6831    error <general>: 
2024-02-17 23:50:37.398 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 883, in load_stream_infos
                                                       return self._get_video_info()
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-17 23:50:37.398 T:6831    error <general>: 
2024-02-17 23:50:37.398 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1323, in _get_video_info
                                                       result = self._request(
                                                                ^^^^^^^^^^^^^^
                                                   
2024-02-17 23:50:37.398 T:6831    error <general>: 
2024-02-17 23:50:37.398 T:6831    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 937, in _request
                                                       raise YouTubeException(error_msg) from error
                                                   
2024-02-17 23:50:37.398 T:6831    error <general>: 
2024-02-17 23:50:37.399 T:6831    error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: Player response failed for video_id: wHengimtTR4, using android client (logged in)
                                                   
2024-02-17 23:50:37.399 T:6831    error <general>: 
2024-02-17 23:50:37.399 T:6831    error <general>: [plugin.video.youtube] None
2024-02-17 23:50:37.409 T:6657    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=wHengimtTR4]

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Check if it works using the latest beta version: https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.3%2Bbeta.3

Note that you will need to login again after installing this beta version.

**Comment by mtneer8O8** [comment]
I also was getting this error relating to "android client" on one of my machines (ARM), but not on an x86 install. Trying the latest beta from MoojMidge here (7.0.3-beta3) seems to have fixed it on Nexus. Great work! Really nice to see active development of this addon.

**Comment by jetfir3** [comment]
Had the exact same issue (started within last ~24hrs) and the 7.0.3-beta3 update also fixed the issue. 

Note:
I was unable to get any of the Matrix beta builds installed+working on Matrix due to `infotagger` and `BaseHTTPServer` dependencies missing which seemed related to Nexus-only builds (?)... but I must admit I did not spend much time digging into that. Pulled the trigger on the Nexus update and all is well.

**Comment by antimatter84** [comment]
I can confirm the beta also fixed the issue for me.

**Comment by MoojMidge** [comment]
Can someone test whether changing the following line in v7.0.2.2 fixes the issue:

https://github.com/anxdpanic/plugin.video.youtube/blob/10fecdecd4e6507cfc50d0b1e9cc468aed2ada88/resources/lib/youtube_plugin/youtube/helper/video_info.py#L606

Change to
```
               'params': '2AMBCgIQBg',
```

The beta version are not ready for release and will take time to be reviewed/distributed, but a simple single line change should be able to made fairly quickly.

**Comment by Line-Noise** [comment]
> Can someone test whether changing the following line in v7.0.2.2 fixes the issue:

Didn't work for me. Same problem. :disappointed:

**Comment by MoojMidge** [comment]
Can someone provide a debug log showing the error? https://kodi.wiki/view/Log_file

**Comment by MossyTC** [comment]
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14334498/kodi.log)


> Can someone provide a debug log showing the error? https://kodi.wiki/view/Log_file

**Comment by MoojMidge** [comment]
@MossyTC - unfortunately the logging didn't provide any more information to help narrow down the fix, but thank you for taking the time to do that, it is much easer to read.

I'll try to create a test v7.0.2.3 release with only minimal changes to see if that is enough to resolve the problem.

**Comment by MossyTC** [comment]
@MoojMidge Maybe add more debug logging to narrow down the cause?

**Comment by MoojMidge** [comment]
@MossyTC - yeah will add some additional logging to compare the v7.0.2.2 request body with the current beta request body. There were lots of changes and i just can't remember what would be specifically relevant to this issue.

**Comment by MoojMidge** [comment]
Unfortunately, it's going to be too time consuming to track down and backport the changes necessary to fix this.

The fix is to upgrade to the latest beta version from https://github.com/anxdpanic/plugin.video.youtube/releases

Will do one more tidy up beta release for testing, before pushing to the Kodi plugin repository. Please test and report any issues with the beta version.

**Comment by madmat01** [comment]
Hey! - Thanks so much for sorting this out. I've upgraded and it's working great again now. 🙏

**Comment by Lreaper** [comment]
Thanks for the update! Can now play videos again with the latest beta release.
I'm having a semi-unrelated issue though, I use kodi-cli.sh to send video links over to kodi, but since updating to this beta release this doesn't seem to be working anymore. Here's the sh script's function that handles this:

```
function play_youtube {

    REGEX="^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*"

    ID=$1

    if [ "$ID" == "" ];
    then
        echo "Syntax $0:$1 <id|url>"
        exit
    fi

    if [[ $ID =~ $REGEX ]]; then
        ID=${BASH_REMATCH[7]}
    fi

    echo -n "Opening video id $ID on $KODI_HOST ..."

    # clear the list
    xbmc_req '{"jsonrpc": "2.0", "method": "Playlist.Clear", "params":{"playlistid":1}, "id": 1}';

    # add the video to the list
    xbmc_req '{"jsonrpc": "2.0", "method": "Playlist.Add", "params":{"playlistid":1, "item" :{ "file" : "plugin://plugin.video.youtube/?action=play_video&videoid='$ID'"}}, "id" : 1}';

    # open the video
    xbmc_req '{"jsonrpc": "2.0", "method": "Player.Open", "params":{"item":{"playlistid":1, "position" : 0}}, "id": 1}';

    echo " done."
}
```

**Comment by MoojMidge** [comment]
@Lreaper - Provide a log in a new issue, as it is not related to this original issue. Don't even know what version you are using when you say "latest beta release"

The supported plugin url query parameters are identified here: https://kodi.wiki/view/Add-on:YouTube

The format you are using is not supported, and you should update it as per the details above.

Support for those old plugin urls were removed in an old beta release. Partial conversion of the old format was added back in a subsequent later beta release, and has been available in the latest stable and beta releases for a while now.
