### ISSUE TITLE
The plugin does not use personal APIs if it is not logged in.

### ISSUE THREAD

**Issue by tomasz-c** [anxdpanic/plugin.video.youtube#587]
### Context

* Add-on Version: 7.0.2.2
* Kodi Version: 20.4
* Kodi GUI Language: PL
* Operating System: LibreELEC
* Operating System Language: EN
------

### Expected Behavior
If I provide the correct personal API keys in the configuration, the plugin should use them regardless of whether I have a YouTube account logged in.
This was the case in previous versions of the plugin.

------

### Current Behavior
If I have the correct API keys configured and I am not logged in to a YouTube account, the plugin uses universal data from the file `plugin.video.youtube/resources/lib/youtube_plugin/__init__.py`
After logging in to your YouTube account, the plugin starts using the individual API keys provided in the configuration.

------

### Steps to Reproduce
1. Generate and configure private personal API keys.
2. Log out your YouTube account.
3. Turn on debug and check what keys the plugin uses or check Google statistics that the personal API is not used.

### Additional Information
I solved it by changing line 234 in the file: `plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__config__.py`
```diff
- youtube_tv['key'], youtube_tv['id'], youtube_tv['secret'] = _api_check.get_api_keys('youtube-tv')
+ youtube_tv['key'], youtube_tv['id'], youtube_tv['secret'] = _api_check.get_api_keys(_current_switch)
```

For me, this causes the plugin to use personal API keys instead of the default ones. I don't know if this is the correct solution. 
Is it possible that this will work by default in future versions of the plugin?

**Comment by MoojMidge** [comment]
> I don't know if this is the correct solution.

Not quite, as this will use a V3 API key for all requests, even V1 requests. I will need to do some testing to see if that works, but previously the personal API key was only used for the V3 requests, if provided. 

> Is it possible that this will work by default in future versions of the plugin?

Yes this will be fixed

**Comment by MoojMidge** [comment]
In v7.0.2.2 can you change
https://github.com/anxdpanic/plugin.video.youtube/blob/10fecdecd4e6507cfc50d0b1e9cc468aed2ada88/resources/lib/youtube_plugin/youtube/client/youtube.py#L1088
To
```
            _params = {'key': self._config.get('key') or self._config_tv['key']}
```
That should fix it in the interim.

**Comment by MusterGit** [comment]
For me, only the solution by @tomasz-c does fix it. Despite not being the correct solution, it will be enough for the time until a proper official fix.

**Comment by MoojMidge** [comment]
@tomasz-c - did the suggested change fix the problem for you?

@MusterGit - that is going to be the "official" fix. If it doesn't work will need some more details i.e. logs, as I am not in a position to be able to test this myself.

**Comment by MusterGit** [comment]
Thanks for digging into this, @MoojMidge. Here are some more details.

I disabled and enabled the addon between the attempts, and I replaced my API Key in the logs with {API_KEY}.

Please tell me if you need further input from me. I'll be glad to help.

### Stock 7.0.2.2:

``` 
2024-02-23 06:34:25.554 T:1478     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on O***** (Kodi-21.0) with Python 3.11.8
                                                   	Path: /kodion/search/query/
                                                   	Params: {'q': 'hyprland'}
2024-02-23 06:34:25.664 T:1478    error <general>: [plugin.video.youtube] Request failed
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 1061, in _request
                                                       result.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key={API_KEY}&q=hyprland&part=snippet&regionCode=US&hl=en_US&relevanceLanguage=en_US&maxResults=50&type=video&order=relevance&safeSearch=none
```
Debug
```
2024-02-23 06:48:01.299 T:2461     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on O***** (Kodi-21.0) with Python 3.11.8
                                                   	Path: /kodion/search/query/
                                                   	Params: {'q': 'hyprland'}
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.login.hash) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.login.password) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.login.username) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.mpd.proxy) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.subtitle.language) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.subtitle.languages) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.video.support.mpd.addon) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (kodion.video.support.mpd.builtin) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (setting) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.api.enable) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.api.key.switch) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.api.key.switch.use) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.api.last.switch) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.client.alternative) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.get.watch_later.playlist.id) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.login.version) was not found.
2024-02-23 06:48:01.301 T:2461    debug <CSettingsManager>: requested setting (youtube.search.remote.friendly) was not found.
2024-02-23 06:48:01.309 T:2461    debug <general>: [plugin.video.youtube] Setting content-type: "videos" for "/kodion/search/query/"
2024-02-23 06:48:01.309 T:2461    debug <general>: [plugin.video.youtube] JSONStore Load |b'/storage/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json'|
2024-02-23 06:48:01.309 T:2461    debug <general>: [plugin.video.youtube] Selecting YouTube config "All"
2024-02-23 06:48:01.309 T:2461    debug <general>: [plugin.video.youtube] User is not logged in
2024-02-23 06:48:01.310 T:2461    debug <general>: [plugin.video.youtube] [data] v3 request: |GET| path: |search| params: |{'q': 'hyprland', 'part': 'snippet', 'regionCode': 'US', 'hl': 'en_US', 'relevanceLanguage': 'en_US', 'maxResults': '50', 'type': 'video', 'order': 'relevance', 'safeSearch': 'none'}| post_data: |None|
2024-02-23 06:48:01.387 T:1011    debug <general>: ------ Window Init (DialogBusy.xml) ------
2024-02-23 06:48:01.439 T:2461    debug <general>: [plugin.video.youtube] Response: <Response [403]>
2024-02-23 06:48:01.442 T:2461    error <general>: [plugin.video.youtube] Request failed
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 1061, in _request
                                                       result.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key={API_KEY}&q=hyprland&part=snippet&regionCode=US&hl=en_US&relevanceLanguage=en_US&maxResults=50&type=video&order=relevance&safeSearch=none
                                                   
2024-02-23 06:48:01.446 T:2461    debug <general>: [plugin.video.youtube] v3 response: Response discarded, is_youtube=False
2024-02-23 06:48:01.446 T:2461    debug <general>: [plugin.video.youtube] Shutdown of Kodion after |0.1481| seconds
2024-02-23 06:48:01.447 T:2461    debug <general>: CPythonInvoker(39, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
```

### With official fix only:

```
2024-02-23 06:37:27.405 T:1679     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on O***** (Kodi-21.0) with Python 3.11.8
                                                   	Path: /kodion/search/query/
                                                   	Params: {'q': 'hyprland'}
2024-02-23 06:37:27.514 T:1679    error <general>: [plugin.video.youtube] Request failed
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 1061, in _request
                                                       result.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key={API_KEY}q=hyprland&part=snippet&regionCode=US&hl=en_US&relevanceLanguage=en_US&maxResults=50&type=video&order=relevance&safeSearch=none
```
Debug
``` 
2024-02-23 06:46:04.479 T:2326     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on O***** (Kodi-21.0) with Python 3.11.8
                                                   	Path: /kodion/search/query/
                                                   	Params: {'q': 'hyprland'}
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.login.hash) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.login.password) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.login.username) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.mpd.proxy) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.subtitle.language) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.subtitle.languages) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.video.support.mpd.addon) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (kodion.video.support.mpd.builtin) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (setting) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.api.enable) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.api.key.switch) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.api.key.switch.use) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.api.last.switch) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.client.alternative) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.get.watch_later.playlist.id) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.login.version) was not found.
2024-02-23 06:46:04.482 T:2326    debug <CSettingsManager>: requested setting (youtube.search.remote.friendly) was not found.
2024-02-23 06:46:04.489 T:2326    debug <general>: [plugin.video.youtube] Setting content-type: "videos" for "/kodion/search/query/"
2024-02-23 06:46:04.489 T:2326    debug <general>: [plugin.video.youtube] JSONStore Load |b'/storage/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json'|
2024-02-23 06:46:04.490 T:2326    debug <general>: [plugin.video.youtube] Selecting YouTube config "All"
2024-02-23 06:46:04.490 T:2326    debug <general>: [plugin.video.youtube] User is not logged in
2024-02-23 06:46:04.490 T:2326    debug <general>: [plugin.video.youtube] [data] v3 request: |GET| path: |search| params: |{'q': 'hyprland', 'part': 'snippet', 'regionCode': 'US', 'hl': 'en_US', 'relevanceLanguage': 'en_US', 'maxResults': '50', 'type': 'video', 'order': 'relevance', 'safeSearch': 'none'}| post_data: |None|
2024-02-23 06:46:04.566 T:1011    debug <general>: ------ Window Init (DialogBusy.xml) ------
2024-02-23 06:46:04.572 T:2326    debug <general>: [plugin.video.youtube] Response: <Response [403]>
2024-02-23 06:46:04.575 T:2326    error <general>: [plugin.video.youtube] Request failed
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 1061, in _request
                                                       result.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key={API_KEY}&q=hyprland&part=snippet&regionCode=US&hl=en_US&relevanceLanguage=en_US&maxResults=50&type=video&order=relevance&safeSearch=none
                                                   
2024-02-23 06:46:04.579 T:2326    debug <general>: [plugin.video.youtube] v3 response: Response discarded, is_youtube=False
2024-02-23 06:46:04.579 T:2326    debug <general>: [plugin.video.youtube] Shutdown of Kodion after |0.1004| seconds
2024-02-23 06:46:04.579 T:2326    debug <general>: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run

``` 

### With @tomasz-c fix only:

```
2024-02-23 06:38:34.876 T:1772     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on O***** (Kodi-21.0) with Python 3.11.8
                                                   	Path: /kodion/search/query/
                                                   	Params: {'q': 'hyprland'}

```
Debug
```
2024-02-23 06:41:39.384 T:2019     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on O***** (Kodi-21.0) with Python 3.11.8
                                                   	Path: /kodion/search/query/
                                                   	Params: {'q': 'hyprland'}
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.login.hash) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.login.password) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.login.username) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.mpd.hdr) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.mpd.limit.30) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.mpd.live_streams) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.mpd.proxy) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.playback.history) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.subtitle.language) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.subtitle.languages) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.video.support.mpd.addon) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (kodion.video.support.mpd.builtin) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (setting) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.api.enable) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.api.key.switch) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.api.key.switch.use) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.api.last.switch) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.client.alternative) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.get.watch_later.playlist.id) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.login.version) was not found.
2024-02-23 06:41:39.387 T:2019    debug <CSettingsManager>: requested setting (youtube.search.remote.friendly) was not found.
2024-02-23 06:41:39.455 T:2019    debug <general>: [plugin.video.youtube] Setting content-type: "videos" for "/kodion/search/query/"
2024-02-23 06:41:39.455 T:2019    debug <general>: [plugin.video.youtube] JSONStore Load |b'/storage/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json'|
2024-02-23 06:41:39.456 T:2019    debug <general>: [plugin.video.youtube] Selecting YouTube config "All"
2024-02-23 06:41:39.456 T:2019    debug <general>: [plugin.video.youtube] User is not logged in
2024-02-23 06:41:39.456 T:2019    debug <general>: [plugin.video.youtube] [data] v3 request: |GET| path: |search| params: |{'q': 'hyprland', 'part': 'snippet', 'regionCode': 'US', 'hl': 'en_US', 'relevanceLanguage': 'en_US', 'maxResults': '50', 'type': 'video', 'order': 'relevance', 'safeSearch': 'none'}| post_data: |None|
2024-02-23 06:41:39.472 T:1011    debug <general>: ------ Window Init (DialogBusy.xml) ------
2024-02-23 06:41:39.886 T:2019    debug <general>: [plugin.video.youtube] [data] v3 response: |200| headers: |{'Content-Type': 'application/json; charset=UTF-8', 'Vary': 'Origin, X-Origin, Referer', 'Content-Encoding': 'gzip', 'Date': 'Fri, 23 Feb 2024 05:41:39 GMT', 'Server': 'scaffolding on HTTPServer2', 'Cache-Control': 'private', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'}|
2024-02-23 06:41:39.904 T:2019    debug <general>: [plugin.video.youtube] Found cached data for videos |eytUmSelFVg, wgajzUIZNh8, wNL6eIoksd8, gOGM0uHCDFk, fOTQmdXkxhc, Cjn0SFyyucY, HhZ_HnqkJoo, WuZ2T6D_9yI, CBlv26LaZyQ, P3rtEDVKstw, 61wGzIv12Ds, plOYeH7atNs, -vJj6iZ0S3Y, q9JKz-Ja4W0, IKDqtGVrIsY, ejJ6h2r8fSM, ZgHX8jPuHjE, iE99GrcZzhs, lfUWwZqzHmA, elOFuFpPSJQ, sDmLCBI9L4E, nohiISbAUe0, TgUl1tMSeJs, PMQf9gAt8FE, 6RNaBRSy-Zs, EujO_5KvCCo, mTzjwVg0ueI, TZMfpNfRKUQ, kHG5czrQ7WA, qb1jrTY72gw, F9ty1_1_ksE, rW3JKs1_oVI, ELEQh0z3lm8, ugrMQyQV6bc, zsyX04mn2_Q, abp9XkQYETQ, V7nP-To0630, uVJWgAzE5N0, CwGlm-rpok4, 9Ic1zzb_xl4, pBkneYtLBJE, -tCdeY1Jqk0, jw5J0rhLQyA, THgo4nBJyg8, ZYlRfTq4QDs, E50pt992Ihc, ptmiPG_V4u8, 5i_LMMXUDJI, otwnzco0HmM, mb8h1-LB9K0|
2024-02-23 06:41:39.917 T:2019    debug <general>: [plugin.video.youtube] Found cached data for channels |UC1yGcBvdPGxRIMT1yo_bKIQ, UCld68syR8Wi-GY_n4CaoJGA, UC0sUzmZ0CHvVCVrpRfGKZfw, UC_zBdZ0_H_jn41FDRG7q4Tw, UCBq5p-xOla8xhnrbhu8AIAg, UCylGUf9BvQooEFjgdNudoQg, UCeZyoDTk0J-UPhd7MUktexw, UCmCOfHxrryLPtOlMfdayJmw, UCMm4cpVg-Z9ihGSavr2QWxQ, UCg6gPGh8HU2U01vaFCAsvmQ, UC6d1AQStNZALSKGnoMbWwrg, UCrjKdwxaQMSV_NDywgKXVmw, UCAIoyqkX4xcjZbp1lp7beiQ, UCwNgCTYI29nTVAnWa7ZyD6A, UC-RCzkKUQkn593IDUBrNEJQ, UCzoVL1aVjec7YKPeG59xKFg, UC5Cukzkdc4hHN1O_psK_C8w, UC-V8FVQCUpRRUPNClviki3w, UC2rUTe_XMx88LR3JLJwyutw, UCtYg149E_wUGVmjGz-TgyNA, UCY_LG2PDPLgpzGDNaXM5iaA, UCmw-QGOHbHA5cDAvwwqUTKQ|
2024-02-23 06:41:39.919 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=eytUmSelFVg|
2024-02-23 06:41:39.919 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=wgajzUIZNh8|
2024-02-23 06:41:39.919 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=wNL6eIoksd8|
2024-02-23 06:41:39.919 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=fOTQmdXkxhc|
2024-02-23 06:41:39.920 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=Cjn0SFyyucY|
2024-02-23 06:41:39.920 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=HhZ_HnqkJoo|
2024-02-23 06:41:39.920 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=WuZ2T6D_9yI|
2024-02-23 06:41:39.920 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=CBlv26LaZyQ|
2024-02-23 06:41:39.921 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=P3rtEDVKstw|
2024-02-23 06:41:39.921 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=61wGzIv12Ds|
2024-02-23 06:41:39.921 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=plOYeH7atNs|
2024-02-23 06:41:39.921 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=-vJj6iZ0S3Y|
2024-02-23 06:41:39.921 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=q9JKz-Ja4W0|
2024-02-23 06:41:39.921 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=IKDqtGVrIsY|
2024-02-23 06:41:39.922 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=ejJ6h2r8fSM|
2024-02-23 06:41:39.922 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=ZgHX8jPuHjE|
2024-02-23 06:41:39.922 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=iE99GrcZzhs|
2024-02-23 06:41:39.922 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=lfUWwZqzHmA|
2024-02-23 06:41:39.922 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=elOFuFpPSJQ|
2024-02-23 06:41:39.923 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=sDmLCBI9L4E|
2024-02-23 06:41:39.923 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=nohiISbAUe0|
2024-02-23 06:41:39.923 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=TgUl1tMSeJs|
2024-02-23 06:41:39.923 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=PMQf9gAt8FE|
2024-02-23 06:41:39.923 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=6RNaBRSy-Zs|
2024-02-23 06:41:39.924 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=EujO_5KvCCo|
2024-02-23 06:41:39.924 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=mTzjwVg0ueI|
2024-02-23 06:41:39.924 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=TZMfpNfRKUQ|
2024-02-23 06:41:39.924 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=kHG5czrQ7WA|
2024-02-23 06:41:39.924 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=qb1jrTY72gw|
2024-02-23 06:41:39.925 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=F9ty1_1_ksE|
2024-02-23 06:41:39.925 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=rW3JKs1_oVI|
2024-02-23 06:41:39.925 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=ELEQh0z3lm8|
2024-02-23 06:41:39.925 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=ugrMQyQV6bc|
2024-02-23 06:41:39.926 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=zsyX04mn2_Q|
2024-02-23 06:41:39.926 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=abp9XkQYETQ|
2024-02-23 06:41:39.926 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=V7nP-To0630|
2024-02-23 06:41:39.926 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=uVJWgAzE5N0|
2024-02-23 06:41:39.926 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=CwGlm-rpok4|
2024-02-23 06:41:39.927 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=9Ic1zzb_xl4|
2024-02-23 06:41:39.927 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=pBkneYtLBJE|
2024-02-23 06:41:39.927 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=-tCdeY1Jqk0|
2024-02-23 06:41:39.927 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=jw5J0rhLQyA|
2024-02-23 06:41:39.927 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=THgo4nBJyg8|
2024-02-23 06:41:39.927 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=ZYlRfTq4QDs|
2024-02-23 06:41:39.928 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=E50pt992Ihc|
2024-02-23 06:41:39.928 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=ptmiPG_V4u8|
2024-02-23 06:41:39.928 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=5i_LMMXUDJI|
2024-02-23 06:41:39.928 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=otwnzco0HmM|
2024-02-23 06:41:39.928 T:2019    debug <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=mb8h1-LB9K0|
2024-02-23 06:41:39.929 T:2019    debug <general>: [plugin.video.youtube] Shutdown of Kodion after |0.5451| seconds
2024-02-23 06:41:39.929 T:2019    debug <general>: CPythonInvoker(33, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
```

**Comment by MoojMidge** [comment]
Thanks for that. Bit confused though, it should work and the equivalent change in the beta version does work.

In the two log excerpts that didn't work can you let me know what the last 3 characters in the API key are? You said that you replaced your API key in the log, but both have been replaced. Are they both the same and both yours?

**Comment by MusterGit** [comment]
Well, actually there was no need to replace the key in the logs, since it's the hardcoded one from `plugin.video.youtube/resources/lib/youtube_plugin/__init__.py`.
Both API keys are ending with `N3g`.

**Comment by MoojMidge** [comment]
Ah, I realise what is wrong now though - I linked to the wrong line to change.

Should have been:
https://github.com/anxdpanic/plugin.video.youtube/blob/10fecdecd4e6507cfc50d0b1e9cc468aed2ada88/resources/lib/youtube_plugin/youtube/client/youtube.py#L1088
Change to:
```
            _params = {'key': self._config.get('key') or self._config_tv['key']}
```

**Comment by MusterGit** [comment]
Many thanks. Is there a way to see which key is used for requests in case of success? Right now, the quota of the hardcoded key is not exceeded, so all requests succeed whatsoever.

UPDATE: Inserted a log_error myself to get the key used. It's indeed using the right one now, ie my personal key. Great support! Looking forward to the next beta with this fix and customizable labels.

**Comment by tomasz-c** [comment]
> @tomasz-c - did the suggested change fix the problem for you?

I couldn't check earlier and now it looks like it's no longer valid.
