### ISSUE TITLE
Unable to play some videos

### ISSUE THREAD

**Issue by JohnnyEn** [anxdpanic/plugin.video.youtube#60]
### Context

Please provide any relevant information about your setup

* Add-on Version: 5.8.8
* Kodi Version: 18.2
* Kodi GUI Language:
* Operating System: LibreElec 9.0.2
* Operating System Language: En

------

### Expected Behavior

Youtube plugin starts a video after sharing video from Yatse remote control

------

### Current Behavior

What is the current behavior?

Currently some videos are experiencing crash of Youtube plugin instead of playing a video. 
Crashes of plugin are random, some videos will play, some not. 
Look at log below:

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open youtube application on android device
2. Choose video with id uQslBusc56g (https://www.youtube.com/watch?v=uWslBusc56g)
3. Click share button
4. Choose Play on Media center (Tested even with Kore remote and text input search, behaviour is same. Probably it's videos related problem)
5. Voila, nothing happens :(

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

2020-12-01 11:39:08.025 T:1336955760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 768, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1024, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 986, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2020-12-01 11:39:08.277 T:1937502224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=uWslBusc56g]

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by JohnnyEn** [comment]
It seems to be fixed with increasing MPEG-DASH to 1080p resolution and updating plugin to 5.8.9-beta1 

Solution found on this URL: https://forum.kodi.tv/showthread.php?tid=356934&page=19
Any ideas why? But it's ready to close issue.

**Comment by Daidalos117** [comment]
I had same problem and complete reinstall of youtube plugin did the trick.

**Comment by teodoryantcheff** [comment]
I think this should be re-opened:

Config:
```
2021-02-13 14:02:16.372 T:1936781328  NOTICE: Starting Kodi (18.9 (18.9.0) Git:newclock5_18.9-Leia). Platform: Linux ARM 32-bit
2021-02-13 14:02:16.372 T:1936781328  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2021-02-13 14:02:16.372 T:1936781328  NOTICE: Kodi compiled 2020-10-25 by GCC 8.3.0 for Linux ARM 32-bit version 4.19.127 (267135)
2021-02-13 14:02:16.372 T:1936781328  NOTICE: Running on LibreELEC (official): 9.2.6, kernel: Linux ARM 32-bit version 4.19.127
2021-02-13 14:02:16.373 T:1936781328  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2021-02-13 14:02:16.373 T:1936781328  NOTICE: Host CPU: ARMv7 Processor rev 5 (v7l), 4 cores available
.....
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: audioencoder.kodi.builtin.aac v1.0.0 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: audioencoder.kodi.builtin.wma v1.0.0 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: driver.dvb.crazycat v9.2.0.0 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: driver.dvb.dvb-latest v9.2.0.0 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: game.controller.default v1.0.8 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: game.controller.snes v1.0.8 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: inputstream.adaptive v2.4.6.1 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: kodi.binary.global.audioengine v1.0.1 installed
2021-02-13 14:02:17.711 T:1936781328  NOTICE: ADDON: kodi.binary.global.filesystem v1.0.2 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.global.general v1.0.3 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.global.gui v5.12.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.global.main v1.0.14 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.global.network v1.0.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.audiodecoder v2.0.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.audioencoder v2.0.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.game v1.1.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.imagedecoder v2.0.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.peripheral v1.3.7 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.pvr v5.10.3 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.screensaver v2.0.0 installed
2021-02-13 14:02:17.712 T:1936781328  NOTICE: ADDON: kodi.binary.instance.vfs v2.0.0 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: kodi.binary.instance.videocodec v1.0.1 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: kodi.binary.instance.visualization v2.0.1 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: kodi.resource v1.0.0 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.album.universal v3.1.4 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.artists.universal v4.3.3 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.allmusic.com v3.2.2 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.fanart.tv v3.6.3 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.imdb.com v3.1.6 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.musicbrainz.org v2.2.4 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.ofdb.de v1.0.5 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.omdbapi.com v1.2.1 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.theaudiodb.com v2.0.3 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.common.themoviedb.org v3.2.13 installed
2021-02-13 14:02:17.713 T:1936781328  NOTICE: ADDON: metadata.local v1.0.0 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: metadata.themoviedb.org v5.2.6 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: metadata.tvdb.com v3.2.8 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: metadata.tvshows.themoviedb.org v3.5.12 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: metadata.universal v5.4.6 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: os.libreelec.tv v9.2 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: os.openelec.tv v9.2 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: peripheral.joystick v1.4.9 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.image.xkcd v1.0.2 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.library.node.editor v1.0.11 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.program.autocompletion v1.0.1 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.program.remote.control.browser v1.4.2 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.video.arenabg v1.0.6a installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.video.vimeo v5.1.4 installed
2021-02-13 14:02:17.714 T:1936781328  NOTICE: ADDON: plugin.video.yatp v3.3.2 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: plugin.video.youtube v6.8.9 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repo.bg.plugins v1.0.0 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repository.kodi.game v1.0.0 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repository.kodi.yatse.tv v1.1.0 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repository.libreelec.tv v9.2.0 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repository.marcelveldt v1.0.2 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repository.romanvm v2.0.0 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: repository.xbmc.org v3.1.6 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.backgroundoverlays.basic v1.0.0 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.languageflags.colour v0.0.4 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.moviegenreicons.transparent v0.0.6 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.moviegenreicons.white v0.0.6 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.musicgenreicons.grey v0.0.6 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.recordlabels.white v0.0.7 installed
2021-02-13 14:02:17.715 T:1936781328  NOTICE: ADDON: resource.images.skinbackgrounds.titanium v1.0.0 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.images.skinicons.wide v1.0.3 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.images.studios.white v0.0.25 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.images.weatherfanart.multi v0.0.6 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.images.weatherfanart.single v0.0.6 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.images.weathericons.default v1.1.8 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.images.weathericons.transparent v0.0.6 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.language.en_gb v2.0.1 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.uisounds.kodi v1.0.0 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.uisounds.nebula v1.0.1 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: resource.uisounds.titan.modern v1.0.0 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: screensaver.xbmc.builtin.black v1.0.33 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: screensaver.xbmc.builtin.dim v1.0.59 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: script.artistslideshow v3.2.2 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: script.extendedinfo v5.6.0 installed
2021-02-13 14:02:17.716 T:1936781328  NOTICE: ADDON: script.favourites v7.1.3 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.globalsearch v8.0.13 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.grab.fanart v0.15.1 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.image.resource.select v2.0.4 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.addon.signals v0.0.6 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.arrow v0.15.5 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.autocompletion v1.1.2 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.backports.functools_lru_cache v1.6.1 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.beautifulsoup v3.2.1 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.beautifulsoup4 v4.6.2 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.certifi v2019.9.11 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.chardet v3.0.4 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.cherrypy v12.0.1 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.dateutil v2.8.1 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.defusedxml v0.6.0 installed
2021-02-13 14:02:17.717 T:1936781328  NOTICE: ADDON: script.module.future v0.17.1 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.garepobg v0.1.4 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.html5lib v0.999.0 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.idna v2.8 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.inputstreamhelper v0.5.2 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.kodi-six v0.1.3 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.kodi65 v1.2.1 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.libtorrent v1.1.1c installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.metadatautils v1.0.37 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.musicbrainz v0.6.0 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.pil v1.1.7 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.pycryptodome v3.4.3 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.pytz v2014.2 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.requests v2.22.0 installed
2021-02-13 14:02:17.718 T:1936781328  NOTICE: ADDON: script.module.requests-cache v0.4.13 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.routing v0.2.3 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.simplecache v1.0.20 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.simplejson v3.16.1 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.simpleplugin v2.3.2 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.six v1.13.0 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.t0mm0.common v2.1.1 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.thetvdb v1.0.27 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.unidecode v1.1.1 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.urllib3 v1.25.6 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.urlresolver v5.1.22 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.urlresolver.yatse v5.0.39 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.module.youtube.dl v20.616.0 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.openweathermap.maps v0.3.1 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.program.driverselect v0.1.6 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.reddit.reader v0.9.9 installed
2021-02-13 14:02:17.719 T:1936781328  NOTICE: ADDON: script.skin.helper.backgrounds v1.0.33 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.skin.helper.service v1.1.31 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.skin.helper.widgets v1.0.38 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.skinshortcuts v1.0.19 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.toolbox v1.1.1 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.tv.show.next.aired v7.0.1 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.videolanguage v0.1.0 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: script.yatse.kodi v1.9.0 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.autosubs v1.0.0 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.library.data.provider v0.3.2 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.libreelec.settings v9.0.0 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.librespot v9.2.0.125 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.skin.widgets v0.0.33 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.subtitles.bsplayer v0.2.1 installed
2021-02-13 14:02:17.720 T:1936781328  NOTICE: ADDON: service.subtitles.unacs v0.0.15h installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.aeon.nox.5 v7.0.1 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.estuary v2.0.27 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.fuse.neue v1.0.4 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.quartz v5.4.11 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.titan.leiabeta v3.8.4 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.unity v0.7.2 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: skin.xperience1080 v7.0.0 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: virtual.rpi-tools v9.2.0.107 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: visualization.shadertoy v1.2.4.1 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: visualization.spectrum v3.0.4.1 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: visualization.waveform v3.1.2.1 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: weather.metoffice v2.0.1 installed
2021-02-13 14:02:17.721 T:1936781328  NOTICE: ADDON: weather.openweathermap.extended v5.0.2 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: weather.weatherbit.io v0.0.20 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: weather.yahoo v5.0.7 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: webinterface.default v18.x-2.4.6 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.addon v18.9 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.core v0.1.0 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.gui v5.14.0 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.json v10.3.0 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.python v2.26.0 installed
2021-02-13 14:02:17.722 T:1936781328  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
```

Videos failing to play with 
`Error Contents: Invalid URL u'http://': No host supplied`

```
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 14:03:06.064 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=86cYacKLw5s]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 14:03:20.609 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=86cYacKLw5s]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 14:07:14.695 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=ssq6X6alZ3w]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 14:07:23.146 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=aXzVF3XeS8M]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 14:07:31.243 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=pyLJIEROIZo]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 14:08:01.442 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=pyLJIEROIZo]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-13 17:02:26.305 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=M5L57eHxIG4]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-14 21:24:45.092 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=M5L57eHxIG4]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-14 21:25:08.116 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=bo8_ILuHHGk]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-14 21:25:23.965 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=TR63LLUUTa4]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-14 21:25:37.278 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=3TAUnYZpMbA]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-14 21:25:51.344 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=EIEiEqKbdZ4]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-14 21:26:07.914 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=6IlEWJ1apcc]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-15 18:54:29.357 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=UhQyZFrYNzw]
--
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
2021-02-15 18:57:13.224 T:1936781328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=UhQyZFrYNzw]
```

While others do play flawlessly.
```

**Comment by anxdpanic** [comment]
@teodoryantcheff 
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by teodoryantcheff** [comment]
@anxdpanic confirmed -- an alpha plugin plays those, no issue.
Thanks! And -- amazing response time!
