### ISSUE TITLE
Can't play any YT videos (it was previously working)

### ISSUE THREAD

**Issue by rwlove** [anxdpanic/plugin.video.youtube#609]
### Context
* Add-on Version: 7.0.0.2
* Kodi Version: 20.4-Nexus
* Kodi GUI Language: Eng
* Operating System: CoreELEC
* Operating System Language: N/A

------

### Expected Behavior

Videos play

------

### Current Behavior

No videos play

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to play a video
2. 
3. 

------

### Log

```
2024-02-29 16:22:33.097 T:11789   error <general>: [plugin.video.youtube] Player response failed for video_id: jHzAqGgIUM0, using android client (logged in)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: Traceback (most recent call last):
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>: 
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>: Traceback (most recent call last):
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 102, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 883, in load_stream_infos
                                                       return self._get_video_info()
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1323, in _get_video_info
                                                       result = self._request(
                                                                ^^^^^^^^^^^^^^
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.098 T:11789   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 937, in _request
                                                       raise YouTubeException(error_msg) from error
                                                   
2024-02-29 16:22:33.098 T:11789   error <general>: 
2024-02-29 16:22:33.099 T:11789   error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: Player response failed for video_id: jHzAqGgIUM0, using android client (logged in)
                                                   
2024-02-29 16:22:33.099 T:11789   error <general>: 
2024-02-29 16:22:33.099 T:11789   error <general>: [plugin.video.youtube] None
2024-02-29 16:22:33.102 T:11619   error <general>: Playlist Player: skipping unplayable item: 37, path [plugin://plugin.video.youtube/play/?video_id=jHzAqGgIUM0]```



------

### Additional Information

I finished watching a video and then no other videos would play, either from 'My Subscriptions' or from 'Subscriptions'.

I restarted Kodi, but the problem persists.

------

**Comment by mogwa1** [comment]
Exact same error here. It worked fine 2 days ago; haven't rebooted in the meantime. It stopped working just now.

**Comment by rwlove** [comment]
Full reboot didn't help and 'Play to Kodi' Chrome plugin fails as well.

**Comment by dkirchberger** [comment]
same here, the problem started 30 minutes ago.. youtube must have changed something.

**Comment by MoojMidge** [comment]
Duplicate of #582

**Comment by MoojMidge** [comment]
Update to latest release from https://github.com/anxdpanic/plugin.video.youtube/releases
