### ISSUE TITLE
Youtube 7.0.3.x not starting / 7.0.2.2 is working but no video playback

### ISSUE THREAD

**Issue by dkirchberger** [anxdpanic/plugin.video.youtube#610]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.2
* Kodi Version:21alpha1
* Kodi GUI Language:German
* Operating System:Mint Linux
* Operating System Language:German

------

### Expected Behavior
Youtube Addin is starting (updated to 7.0.3.2 because video playback failed in 7.0.2.2

Please describe the behavior you are expecting.

starting youtube -> error see logs:

2024-02-29 23:44:36.065 T:7367    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'InvalidJSONError' from 'requests.exceptions' (/usr/lib/python3/dist-packages/requests/exceptions.py)
                                                   Traceback (most recent call last):
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 13, in <module>
                                                       from youtube_plugin import youtube
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/__init__.py", line 13, in <module>
                                                       from .provider import Provider
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 17, in <module>
                                                       from .client import YouTube
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__init__.py", line 13, in <module>
                                                       from .youtube import YouTube
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 20, in <module>
                                                       from .login_client import LoginClient
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/login_client.py", line 15, in <module>
                                                       from .__config__ import (
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__config__.py", line 15, in <module>
                                                       from ...kodion.context import XbmcContext
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 14, in <module>
                                                       from .abstract_provider import (
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 17, in <module>
                                                       from .items import (
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/__init__.py", line 24, in <module>
                                                       from .utils import from_json
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/utils.py", line 19, in <module>
                                                       from .video_item import VideoItem
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/video_item.py", line 18, in <module>
                                                       from ..utils import duration_to_seconds, seconds_to_duration
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/__init__.py", line 31, in <module>
                                                       from .service_monitor import ServiceMonitor
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/service_monitor.py", line 18, in <module>
                                                       from ..network import get_http_server, is_httpd_live
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/__init__.py", line 12, in <module>
                                                       from .http_server import get_client_ip_address, get_http_server, is_httpd_live
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 19, in <module>
                                                       from .requests import BaseRequestsClass
                                                     File "/home/dani/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 17, in <module>
                                                       from requests.exceptions import InvalidJSONError, RequestException
                                                   ImportError: cannot import name 'InvalidJSONError' from 'requests.exceptions' (/usr/lib/python3/dist-packages/requests/exceptions.py)
                                                   -->End of Python script error report<--
                                                   
2024-02-29 23:44:36.138 T:7366    error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2024-02-29 23:44:36.144 T:7278    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
You need to update your distribution Python requests package.

Kodi is using your distribution Python packages rather than the Kodi module, due to a bug that was already fixed in a later version than the almost 1 year old Alpha 1 version you are using.
