### ISSUE TITLE
Recomedations not working

### ISSUE THREAD

**Issue by Mutronics** [anxdpanic/plugin.video.youtube#64]
Add-on Version: GIT  eff6401
Kodi Version: 18.9
Kodi GUI Language: Russian
Operating System: COREELEC
Operating System Language: EN
`
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 796, in _on_yt_specials
                                                return yt_specials.process(category, self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 304, in process
                                                return _process_recommendations(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 67, in _process_recommendations
                                                json_data = provider.get_client(context).get_activities('home', page_token=page_token)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 433, in get_activities
                                                recommended = self._get_recommendations_for_home()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 329, in _get_recommendations_for_home
                                                history = self.get_watch_history()
                                            AttributeError: 'YouTube' object has no attribute 'get_watch_history'
`

**Comment by anxdpanic** [comment]
fixed as well as I could in beta3. see #68 for more information
