### ISSUE TITLE
Error message when rating a video

### ISSUE THREAD

**Issue by baltzis** [anxdpanic/plugin.video.youtube#666]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4+nexus.1
* Kodi Version: 20.1
* Kodi GUI Language: Greek
* Operating System: Windows
* Operating System Language: Greek

------

### Expected Behavior

Rating a video should not produce any errors.

------

### Current Behavior

Rating any video produces an error.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. On any selected video, press C
2. Select "More"
3. Select "Rate"
4. Select any option

------

### Log

2024-03-30 20:46:00.335 T:34916    info <general>: [plugin.video.youtube] Running: YouTube (7.0.4+nexus.1) on Nexus (Kodi-20.1) with Python 3.8.15
                                                   Path: /video/more/
                                                   Params: {'video_id': 'KmFkmj5pA-M', 'logged_in': True, 'refresh': False}
2024-03-30 20:46:04.231 T:27296    info <general>: [plugin.video.youtube] Running: YouTube (7.0.4+nexus.1) on Nexus (Kodi-20.1) with Python 3.8.15
                                                   Path: /video/rate/
                                                   Params: {'video_id': 'KmFkmj5pA-M', 'refresh': False}
2024-03-30 20:46:07.445 T:27296   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bool' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\plugin.py", line 17, in <module>
                                                       plugin_runner.run(youtube.Provider())
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\plugin_runner.py", line 61, in run
                                                       plugin.run(provider, context)
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\plugin\xbmc\xbmc_plugin.py", line 63, in run
                                                       results = provider.navigate(context)
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 125, in navigate
                                                       result = method(context, re_match)
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 302, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 678, in _on_video_x
                                                       return yt_video.process(method, self, context, re_match)
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_video.py", line 121, in process
                                                       return _process_rate_video(provider, context, re_match)
                                                     File "C:\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_video.py", line 68, in _process_rate_video
                                                       if response.get('status_code') != 204:
                                                   AttributeError: 'bool' object has no attribute 'get'
                                                   -->End of Python script error report<--

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Will be fixed in next release.

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.3
