### ISSUE TITLE
7.0.7 beta 2 throws exception

### ISSUE THREAD

**Issue by AlexNk** [anxdpanic/plugin.video.youtube#769]
### Context

* Add-on Version: 7.0.7 beta 2 - unofficial
* Kodi Version: 20.3.0 Git:20.3-Nexus
* Kodi GUI Language: English
* Operating System: LibreELEC (official): 11.0.6, kernel: Linux x86 64-bit version 6.1.74
* Operating System Language: English

### Expected Behavior

Normal functioning after installation

### Current Behavior

Exception is thrown when trying to open/configure the plugin

### Steps to Reproduce

1.  Up[date the plugin to 7.0.7 beta 2 from zip
2. Observe the exception
3. Try to open the plugin configuration
4. Observe the same exception

### Log

```
2024-05-23 15:11:47.527 T:1570788   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot create weak reference to 'xbmcaddon.Addon' object
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 13, in <module>
                                                       from youtube_plugin.kodion import plugin_runner
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 18, in <module>
                                                       from ..youtube import Provider
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/__init__.py", line 13, in <module>
                                                       from .provider import Provider
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 19, in <module>
                                                       from .client import APICheck, YouTube
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__init__.py", line 14, in <module>
                                                       from .youtube import YouTube
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 19, in <module>
                                                       from .login_client import LoginClient
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/login_client.py", line 15, in <module>
                                                       from .request_client import YouTubeRequestClient
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/request_client.py", line 12, in <module>
                                                       from ..youtube_exceptions import YouTubeException
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/youtube_exceptions.py", line 14, in <module>
                                                       from ..kodion.network import InvalidJSONError
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/__init__.py", line 12, in <module>
                                                       from .http_server import (
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 34, in <module>
                                                       class RequestHandler(BaseHTTPRequestHandler, object):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 36, in RequestHandler
                                                       requests = BaseRequestsClass()
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 46, in __init__
                                                       settings = XbmcPluginSettings()
                                                                  ^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/settings/xbmc/xbmc_plugin_settings.py", line 83, in __init__
                                                       self.flush(xbmc_addon, fill=True)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/settings/xbmc/xbmc_plugin_settings.py", line 114, in flush
                                                       self._proxy = SettingsProxy(ref(xbmc_addon))
                                                                                   ^^^^^^^^^^^^^^^
                                                   TypeError: cannot create weak reference to 'xbmcaddon.Addon' object
                                                   -->End of Python script error report<--
                                                   
2024-05-23 15:11:47.613 T:757     error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2024-05-23 15:11:47.613 T:757     error <general>: GetDirectory - Error getting library://video/YouTube.xml/

```

**Comment by benyamin-codez** [comment]
I can confirm I have the same problem, but I installed from the test repo instead.

Normal log, showing exception:

```
info <general>: CAddonMgr::FindAddon: plugin.video.youtube v7.0.7+beta.2 installed
warning <general>: CGUIMediaWindow::OnMessage - updating in progress
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot create weak reference to 'xbmcaddon.Addon' object
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/service.py", line 13, in <module>
                                                       from youtube_plugin.kodion import service_runner
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/service_runner.py", line 23, in <module>
                                                       from .monitors import PlayerMonitor, ServiceMonitor
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/__init__.py", line 14, in <module>
                                                       from .service_monitor import ServiceMonitor
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/service_monitor.py", line 18, in <module>
                                                       from ..network import get_connect_address, get_http_server, httpd_status
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/__init__.py", line 12, in <module>
                                                       from .http_server import (
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 34, in <module>
                                                       class RequestHandler(BaseHTTPRequestHandler, object):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 36, in RequestHandler
                                                       requests = BaseRequestsClass()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 46, in __init__
                                                       settings = XbmcPluginSettings()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/settings/xbmc/xbmc_plugin_settings.py", line 83, in __init__
                                                       self.flush(xbmc_addon, fill=True)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/settings/xbmc/xbmc_plugin_settings.py", line 114, in flush
                                                       self._proxy = SettingsProxy(ref(xbmc_addon))
                                                   TypeError: cannot create weak reference to 'xbmcaddon.Addon' object
                                                   -->End of Python script error report<--
```

**Comment by Mo1967** [comment]
Same on Android when upgrade with .zip from  v7.0.7+beta.1 to  v7.0.7+beta.2
Debug-Log: 
[kodi(1).log](https://github.com/anxdpanic/plugin.video.youtube/files/15419914/kodi.1.log)

**Comment by MoojMidge** [comment]
Another issue from trying to support Kodi 18

Fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.3
