### ISSUE TITLE
Watch later, delete problem

### ISSUE THREAD

**Issue by timur-davletshin** [anxdpanic/plugin.video.youtube#776]
* Add-on Version: 7.0.6.3
* Kodi Version: 21.0
* Kodi GUI Language: English
* Operating System: Libreelec 12.0
* Operating System Language: English

------

### Current Behavior

Whenever I delete video from Watch later list (via GUI menu) the list refreshes and, for some reason, switches from simple list view to miniatures.

**Comment by timur-davletshin** [comment]
Happens in 7.0.7 too on any Refresh list action (Right click -> Refresh).

**Comment by MoojMidge** [comment]
Can you see if it is fixed in https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

**Comment by timur-davletshin** [comment]
Indeed now it is fixed.

**Comment by alphaleonis** [comment]
@MoojMidge With 7.0.7.1 I get the following error in the log when attempting to remove a video from my Watch Later playlist:
```
2024-06-02 13:22:43.182 T:1948     info <general>: [plugin.video.youtube] Running: YouTube (7.0.7.1) on Omega (Kodi-21.0) with Python 3.8.15
                                                   Path: /playlist/remove/video/
                                                   Params: {'playlist_id': 'PLXXXXXXXXXXXXXXXX', 'video_id': 'UEw1RUE4OEU1QjNBNDQ2QkM0LjA2OTBFRjhBQzg0RTAxQkM', 'video_name': 'TEST VIDEO', 'reload_path': '/channel/mine/playlist/PLXXXXXXXXXXXXXXXX/'}
2024-06-02 13:22:43.184 T:1948    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'XbmcContext' object has no attribute 'get_listitem_detail'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\plugin_runner.py", line 63, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\plugin\xbmc\xbmc_plugin.py", line 168, in run
                                                       result, options = provider.navigate(context)
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 142, in navigate
                                                       result = method(context, re_match)
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 348, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 734, in _on_playlist_x
                                                       return yt_playlist.process(method, category, self, context)
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_playlist.py", line 310, in process
                                                       return _process_remove_video(provider, context)
                                                     File "C:\Users\alpha\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_playlist.py", line 69, in _process_remove_video
                                                       listitem_playlist_item_id = context.get_listitem_detail('playlist_item_id')
                                                   AttributeError: 'XbmcContext' object has no attribute 'get_listitem_detail'
                                                   -->End of Python script error report<--
```

**Comment by timur-davletshin** [comment]
@alphaleonis yep, I can confirm. Now deleting videos from Watch later gives error message mentioned by you.

**Comment by Mo1967** [comment]
Can also confirm this behaviour in v7.0.7.1 including fix 7db63bf
Log below
[kodi(1).log](https://github.com/user-attachments/files/15688116/kodi.1.log)

**Comment by MoojMidge** [comment]
There are a bunch of commits and uncommitted changes that I need to sort out and which I haven't had a chance to push to an proper release. 

In the meantime can try an update v7.0.7.1 test release (not the same as the older test release and includes fixes for this and some other things).

https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

**Comment by Mo1967** [comment]
> There are a bunch of commits and uncommitted changes that I need to sort out and which I haven't had a chance to push to an proper release.
> 
> In the meantime can try an update v7.0.7.1 test release (not the same as the older test release and includes fixes for this and some other things).
> 
> https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

@MoojMidge  please find first test trial with v7.0.7.1 released today in the Log
[kodi(2).log](https://github.com/user-attachments/files/15702227/kodi.2.log)

Thanks a lot for your support

**Comment by MoojMidge** [comment]
This is embarrassing... just no time at the moment to look over things properly.

Can you try again. Test release updated https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

**Comment by Mo1967** [comment]
> This is embarrassing... just no time at the moment to look over things properly.
> 
> Can you try again. Test release updated https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

Now, working for each user. Thanks for your help.
[kodi(1).log](https://github.com/user-attachments/files/15746202/kodi.1.log)

**Comment by DjDiabolik** [comment]
@MoojMidge ever as purpose test.... installed the 7.0.8 beta 1.
Used for about 40 minutes...... general usage it's very the 7.0.7.1 released on your fork.
All three variat of "Search" feature back to work........ remain the little trouble on "Watch Later" Feature:
Apparently you can add video to "Watch Later" playlist whitout any issue.. inside kodi.log appears this:
```
2024-06-13 17:09:43.954 T:361      info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.1.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /
                                                   Params: {}
2024-06-13 17:09:46.531 T:21       info <general>: CActiveAESink::OpenSink - initialize sink
2024-06-13 17:09:46.578 T:21       info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_0e.0.hdmi-surround in pcm mode with Buffersize 150 ms Periodsize 50 ms
2024-06-13 17:09:49.602 T:376      info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.1.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /special/new_uploaded_videos_tv_filtered/
                                                   Params: {'category_label': 'Le mie iscrizioni (filtrate)'}
2024-06-13 17:09:50.893 T:376     error <general>: [plugin.video.youtube] Python strptime bug workaround - https://github.com/python/cpython/issues/71587
2024-06-13 17:09:55.820 T:403      info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.1.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /playlist/add/video/
                                                   Params: {'playlist_id': 'PLDxxECEFxxDFxBxC', 'video_id': 'mqNi2J6lkfM'}
```
I have masked my watchlater playlist id whit some "xx" the problems appears when you try to open the "Watch Later" playlist from main meù.. kodi.log appear:
```
2024-06-13 17:17:29.118 T:565      info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.1.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /channel/mine/playlist/PLDxxECEFxxDFxxBxC/
                                                   Params: {'category_label': 'Guarda più tardi'}
2024-06-13 17:17:29.120 T:565   warning <general>: [plugin.video.youtube] v3 response: Items list is empty
2024-06-13 17:17:29.120 T:577     error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/channel/mine/playlist/PLDxxECEFxxDF0xBxC/?category_label=Guarda%20pi%c3%b9%20tardi
2024-06-13 17:17:29.120 T:7       error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/channel/mine/playlist/PLDxxECEFxxDFxxBxC/?category_label=Guarda%20pi%c3%b9%20tardi) failed
2024-06-13 17:17:29.121 T:565      info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.1.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /
                                                   Params: {}
```
Everything seems to work if the same playlist contains two or more videos.....

**Comment by DjDiabolik** [comment]
and i can add one things... @MoojMidge because why didn't I open a new issue for this?
- simply because we are facing a beta :) which I must say, besides this, it works, in my opinion, really very well.
- Because this is an issue related to Watch later playlist... also not related issue.
- But most likely it's because I know you already know about the problem :)

**Comment by MoojMidge** [comment]
The first page of a playlist is currently cached for 5 minutes. If you have nothing in your watch later playlist and try to open it then you will save an empty list into the cache. When you add something to that playlist it won't show up until 5 minutes later.

It is unrelated to this issue, but a few things can be improved:

- invalidate the playlist cache when a modification is known to have occurred.
- allow empty lists to be displayed with a dummy entry to allow the list to be refreshed manually.
