### ISSUE TITLE
7.0.8 beta 2 - always considering the beta factor.. some various video can't playable due to a strange error in the kodi.log..

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#801]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.8 beta 2
* Kodi Version: 21 flatpak
* Kodi GUI Language: italian
* Operating System: ubuntu 22.04.4 lts
* Operating System Language: italian

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

This is an example error obtain when i try some video in this case from "My Subscription":
```
2024-06-18 00:16:28.979 T:41082    info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.2.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /play/
                                                   Params: {'video_id': 'JNYbugAwaO8'}
2024-06-18 00:16:29.404 T:41082   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: expected string or bytes-like object, got 'dict'
                                                   Traceback (most recent call last):
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 63, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 168, in run
                                                       result, options = provider.navigate(context)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 155, in navigate
                                                       result = method(context, re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 361, in wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 705, in on_play
                                                       return yt_play.play_video(self, context)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 67, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 202, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 756, in load_stream_infos
                                                       return self._get_video_info()
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1572, in _get_video_info
                                                       stream_list.extend(self._create_stream_list(
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1053, in _create_stream_list
                                                       itag=itag, stream=redact_ip_from_url(stream_map)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/methods.py", line 319, in redact_ip_from_url
                                                       return re.sub(r'([?&/])ip([=/])[^?&/]+', '\g<1>ip\g<2><redacted>', url)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
                                                       return _compile(pattern, flags).sub(repl, string, count)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: expected string or bytes-like object, got 'dict'
                                                   -->End of Python script error report<--
                                                   
2024-06-18 00:16:29.504 T:7       error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=JNYbugAwaO8]

```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

as I say in the title there is always the beta factor to take into consideration. generally the addons seem to work well but as I say some playbacks of some videos go into error and cause that portion of text in the kodi.log

It's fix in some way ? I hope this feedback it's usefull to make ever better this addons.

------

**Comment by ChrisKar96** [comment]
Have the exact same issue. After some testing reached the following conclusion. 

Switching to alternate client details #2 helped. Default and alternate #1 result in the described issue.

**Comment by Abbaddon911** [comment]
Alternate Client 2 is NOT a solution as it limits playback, at least on my machine, to 720p and only gets 1 audio track (in case there are multiple) which is often an AI translated audio track that I don't understand.

Similar with "Standard". There I get full 1080p, but it also sometimes fetches only one audio track, which is usually an AI translated audio track I don't understand.

The only working mode, in a sense of 1080p and ALL audio tracks, so I can switch if needed, is Alternate 1, which seems to be also affected with the latest beta.

Then again, it's a beta for a reason.

**Comment by XxAcielxX** [comment]
**7.0.8+beta.2**
I'm facing the same issue. It started 2-3h ago, and I can't pay videos at all now.

**Comment by DjDiabolik** [comment]
Hello friends.... I guys in the videos where I'm having this error I'm just turning off the MPEG-DASH and all video seem back to watchable.
Without MPEG-DASH instead apparently the maximum resolution can obtain it's 720P but it's better than nothings.

So.. the question it's.. in your system you have MPEG-DASH enabled or not ?

**Comment by XxAcielxX** [comment]
> So.. the question it's.. in your system you have MPEG-DASH enabled or not ?

I have it enabled.

**Comment by MoojMidge** [comment]
Should be fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8%2Bbeta.3

**Comment by DjDiabolik** [comment]
whit beta 3 sometime i have to start reproduction of same video twice and the seconds time it's work.
The first time the notification telling you to check the kodi.log does not appear but the error appears on the screen: playback failed...

@MoojMidge 

All of this also whit MPEG-DASH Enabled.

**Comment by DjDiabolik** [comment]
@MoojMidge i don't have idea if it's usefull... but this is portion of kodi.log when the playback fail:
```
2024-06-19 12:07:44.473 T:3626     info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.3.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /play/
                                                   Params: {'video_id': 'z0gThd195aM'}
2024-06-19 12:07:45.093 T:7        info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=z0gThd195aM
2024-06-19 12:07:45.093 T:3629  warning <general>: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
2024-06-19 12:07:45.094 T:3629     info <general>: Creating InputStream
2024-06-19 12:07:45.096 T:3629     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-06-19 12:07:45.096 T:3629    error <general>: CCurlFile::CReadState::FillBuffer - (0x711e4043db90) Failed: Couldn't connect to server(7)
2024-06-19 12:07:45.096 T:3629    error <general>: CCurlFile::Open - <http://127.0.0.1:50152/youtube/manifest/dash/z0gThd195aM.mpd> Failed with code 0:
                                                   
2024-06-19 12:07:45.096 T:3629    error <general>: AddOnLog: inputstream.adaptive: Open: CURLOpen failed
2024-06-19 12:07:45.096 T:3629    error <general>: AddOnLog: inputstream.adaptive: Download failed, internal error: http://127.0.0.1:50152/youtube/manifest/dash/z0gThd195aM.mpd
2024-06-19 12:07:45.096 T:3629    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=z0gThd195aM]
2024-06-19 12:07:45.097 T:3629     info <general>: CVideoPlayer::OnExit()
2024-06-19 12:07:45.097 T:3629     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-06-19 12:07:45.212 T:7        info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-06-19 12:07:45.216 T:7        info <general>: CVideoPlayer::CloseFile()
2024-06-19 12:07:45.223 T:7        info <general>: VideoPlayer: waiting for threads to exit
2024-06-19 12:07:45.223 T:7        info <general>: VideoPlayer: finished waiting
2024-06-19 12:07:48.218 T:3635     info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.3.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /play/
                                                   Params: {'video_id': 'z0gThd195aM'}
2024-06-19 12:07:48.868 T:7        info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=z0gThd195aM
2024-06-19 12:07:48.869 T:3638     info <general>: Creating InputStream
2024-06-19 12:07:48.871 T:3638     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-06-19 12:07:48.875 T:3638     info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 9, Type: VOD)
2024-06-19 12:07:48.875 T:3638     info <general>: Creating Demuxer
2024-06-19 12:07:48.875 T:3638     info <general>: Opening stream: 1001 source: 256
2024-06-19 12:07:48.977 T:3638     info <general>: Creating video codec with codec id: 167
2024-06-19 12:07:48.977 T:3638     info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: Google VP9
2024-06-19 12:07:48.977 T:3638     info <general>: Creating video thread
2024-06-19 12:07:48.977 T:3642     info <general>: running thread: video_thread
2024-06-19 12:07:48.977 T:3638     info <general>: Opening stream: 1008 source: 256
2024-06-19 12:07:49.033 T:3638     info <general>: Finding audio codec for: 86076
2024-06-19 12:07:49.034 T:3638     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder opus
2024-06-19 12:07:49.034 T:3638     info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-06-19 12:07:49.034 T:3638     info <general>: Creating audio thread
2024-06-19 12:07:49.034 T:3645     info <general>: running thread: CVideoPlayerAudio::Process()
2024-06-19 12:07:49.034 T:3638     info <general>: Opening stream: 1009 source: 256
2024-06-19 12:07:49.150 T:3638     info <general>: CDVDSubtitlesLibass: Using libass version 1502000
2024-06-19 12:07:49.151 T:3638     info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2024-06-19 12:07:49.151 T:3638     info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2024-06-19 12:07:49.151 T:3638     info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2024-06-19 12:07:49.317 T:3638     info <general>: CDVDSubtitlesLibass: Creating new ASS track
2024-06-19 12:07:49.388 T:3645     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder opus
2024-06-19 12:07:49.389 T:3645     info <general>: Creating audio stream (codec id: 86076, channels: 2, sample rate: 48000, no pass-through)
2024-06-19 12:07:49.389 T:21       info <general>: CActiveAESink::OpenSink - initialize sink
2024-06-19 12:07:49.390 T:3683     info <general>: COutput::OnStartup: Output Thread created
2024-06-19 12:07:49.437 T:21       info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_0e.0.hdmi-surround in pcm mode with Buffersize 150 ms Periodsize 50 ms
2024-06-19 12:07:49.489 T:7        info <general>: GL: Selecting YUV 2 RGB shader
2024-06-19 12:07:49.490 T:7        info <general>: GL: Using GL_ARB_pixel_buffer_object
2024-06-19 12:07:49.490 T:7        info <general>: Using GL_TEXTURE_2D
2024-06-19 12:07:49.641 T:3642     info <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 33363
2024-06-19 12:07:52.440 T:7        info <general>: CVideoPlayer::CloseFile()
2024-06-19 12:07:52.445 T:3638     info <general>: CVideoPlayer::OnExit()
2024-06-19 12:07:52.447 T:7        info <general>: VideoPlayer: waiting for threads to exit
2024-06-19 12:07:52.447 T:3638     info <general>: Closing stream player 1
2024-06-19 12:07:52.448 T:3638     info <general>: Waiting for audio thread to exit
2024-06-19 12:07:52.459 T:3645     info <general>: thread end: CVideoPlayerAudio::OnExit()
2024-06-19 12:07:52.459 T:3638     info <general>: Closing audio device
2024-06-19 12:07:52.504 T:21       info <general>: CActiveAESink::OpenSink - initialize sink
2024-06-19 12:07:52.504 T:3638     info <general>: Deleting audio codec
2024-06-19 12:07:52.504 T:3638     info <general>: Closing stream player 2
2024-06-19 12:07:52.504 T:3638     info <general>: waiting for video thread to exit
2024-06-19 12:07:52.525 T:3642  warning <general>: OutputPicture - timeout waiting for buffer
2024-06-19 12:07:52.526 T:3642     info <general>: thread end: video_thread
2024-06-19 12:07:52.526 T:3638     info <general>: deleting video codec
2024-06-19 12:07:52.527 T:3638     info <general>: VAAPI::Close
2024-06-19 12:07:52.527 T:3683     info <general>: COutput::OnExit: Output Thread terminated
2024-06-19 12:07:52.527 T:3638     info <general>: VAAPI::Close - closing decoder context
2024-06-19 12:07:52.532 T:3638     info <general>: Closing stream player 3
2024-06-19 12:07:52.537 T:3638     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-06-19 12:07:52.538 T:7        info <general>: VideoPlayer: finished waiting
2024-06-19 12:07:52.538 T:7        info <general>: CVideoPlayer::CloseFile()
2024-06-19 12:07:52.538 T:7        info <general>: VideoPlayer: waiting for threads to exit
2024-06-19 12:07:52.538 T:7        info <general>: VideoPlayer: finished waiting
2024-06-19 12:07:52.555 T:7       error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-06-19 12:07:52.752 T:21       info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_0e.0.hdmi-surround in pcm mode with Buffersize 150 ms Periodsize 50 ms
2024-06-19 12:07:53.876 T:4549     info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.3.unofficial.1) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /channel/mine/playlist/PLD43ECEF06DF03B5C/
                                                   Params: {'category_label': 'Guarda più tardi', 'refresh': 2}
```

**Comment by DjDiabolik** [comment]
127.0.0.1... it's localhost. If I'm not mistaken there is a setting related to this IP address. Maybe it's need to made some change in this setting ?

**Comment by MoojMidge** [comment]
A whole bunch of people have commented or reacted to this issue, but no one has provided a debug log, let alone a full debug log.

Fixing the original error in the log snippet is trivial, but there is a reason it was being triggered in the first place.

Without a log I can't figure out what combination of settings you are all using that triggers this.

I'm guessing it is because you were all limiting resolution to 1080p and using MPEG-DASH video, which I attempted to take account of, but who knows if there is not some other issue as well?

If you have an issue you need to provide the information necessary to fix it. 

> Maybe it's need to made some change in this setting ?

This is a separate issue related to stopping and starting the http server. On your system evidently it takes longer to restart the server than it does to start playing the video.

Can it be fixed? Yes, easily, but I need a debug log.

**Comment by DjDiabolik** [comment]
> A whole bunch of people have commented or reacted to this issue, but no one has provided a debug log, let alone a full debug log.
> 
> Fixing the original error in the log snippet is trivial, but there is a reason it was being triggered in the first place.
> 
> Without a log I can't figure out what combination of settings you are all using that triggers this.
> 
> I'm guessing it is because you were all limiting resolution to 1080p and using MPEG-DASH video, which I attempted to take account of, but who knows if there is not some other issue as well?
> 
> If you have an issue you need to provide the information necessary to fix it.
> 
> > Maybe it's need to made some change in this setting ?
> 
> This is a separate issue related to stopping and starting the http server. On your system evidently it takes longer to restart the server than it does to start playing the video.
> 
> Can it be fixed? Yes, easily, but I need a debug log.

mmmmm.... about this issue whit beta 3 i thinks i can try to obtain a full debug log.

if i do it i will try to attach here or in a new issue.....

llet's say that in reporting the portion of the kodi.log it is in the idea that you can reproduce the same problem in your kodi configuration/installation and try to found a fix :)

Anyway, if the problem is the http server, why wasn't beta 2 affected by it? can you explain simply can try to understand ?

**Comment by MoojMidge** [comment]
> llet's say that in reporting the portion of the kodi.log it is in the idea that you can reproduce the same problem in your kodi configuration/installation and try to found a fix :)

Something happens on your system, that you already have a record of, and which you can easily get more details for, but you want me to try and replicate it instead?

For some things a snippet of a normal log is sufficient, but not for this, which is why I have asked for more details. Not only can I not replicate it, but it is also means that instead of trying to fix the problem, I'm spending time trying to get information to find the problem. 

If details are not provided then I will be forced to simply close/ignore issues because they are not reproducible.


> Anyway, if the problem is the http server, why wasn't beta 2 affected by it? can you explain simply can try to understand ?

Because you had the error you initially reported instead.

**Comment by DjDiabolik** [comment]
> If details are not provided then I will be forced to simply close/ignore issues because they are not reproducible.

I'm sorry but it was obvious that you couldn't reproduce the error.

You thinks it's same things if i enable the debug log level "on the fly" (whitout enable debug and restart kodi to get usually the full debug) only when i can reproduce this error ? Only because until 5 minutes ago I realized that now he does it not every video but randomly.. sometime after one or two video sometime immediatelly whit two video in row. It seems as if the problem is temporary right now....

**Comment by MoojMidge** [comment]
The http server will currently stop after 30s of idle time and won't restart until needed for playback. If it didn't restart in time you will get this problem. At least that is what I am guessing is happening, but need a debug log to confirm.

What you can do is:

1. Enable debug logging while successfully playing a video
2. Stop the video
3. Wait at least 30s, 60s to be sure
4. Try to play another video and you should see the problem re-occur
5. Try to play another video within 30s of the previous attempt and it should work

If you can get a log of that it would be very helpful

**Comment by kuraikaze** [comment]
[Add-on Version: 7.0.8+beta.3.unofficial.1]

I'm having the same issue, so time for a debug log :)

[Gist of debug kodi.log](https://gist.github.com/kuraikaze/eb9b0851be6e1f92faf995a87ce161cd#file-kodi-log)

There was a bit of faffing around with resetting viewed-status/resume-point/refreshing-subscription-list etc, in the UI, so I picked out some relevant timestamps, more or less according to the actions you requested above:-

Line:3237  - 2024-06-20 08:58:53.166 - start video (success)
Line:3814  - 2024-06-20 08:59:53.962 - stop video 
Wait > 30s, 60s 
Line:5431  - 2024-06-20 09:02:50.551 - restart video (failed)
Wait > 30s, 60s 
Line:5716  - 2024-06-20 09:20:35.019 - start video (success)
Line:6312  - 2024-06-20 09:22:00.072 - stop video
Wait > 30s, 60s 
Line:10107 - 2024-06-20 09:30:03.287 - start video (failed)
Wait < 30s, 60s 
Line:10350 - 2024-06-20 09:30:18.927 - start video (success)

Hope that helps

**Comment by MoojMidge** [comment]
> Hope that helps

It does thanks.

Looks like the issue is not that it takes the http server too long to start up (couldn't figure out how this was a possible problem), but that the JSON-RPC request that is used to signal that the http server is required is getting stuck in a queue behind a whole bunch of other requests that your system is processing.

There are enough other requests being processed that Kodi doesn't get to the request to start the http server until after it has already tried to play it, which then fails.

Will be a bit tricky to resolve neatly

**Comment by kuraikaze** [comment]
Personally I'd be quite willing to accept a second or so of wait-time added for the queue to be cleared and start of playback, assuming adding an artificial delay would even help.
I'm guessing that would not be a universally popular solution, and it's certainly not elegant or pleasing from a coder POV :smirk:

As it is I'm constantly annoyed by Youtubers who cut their videos too tight at the start - they start speaking *instantly*, and I usually miss the first couple of words as there seems to be some video/audio latency in my system between initiating Youtube playback on Kodi on the miniPC->AV-Receiver->TV chain and start of output - the first second or so of content seemingly gets blackholed somewhere along the way.  On the other hand - maybe I'd just end up with the *same* missed start ... but with an additional second added. :disappointed:

**Comment by XxAcielxX** [comment]
For me many videos keeps loading for ~45secs, and then the `Playback failed` pop-up appears. Then I play the video again, now it plays it. This started after version 7.0.2 I think. It getting very annoying now.

**Comment by MoojMidge** [comment]
@kuraikaze - the simplest option would have been simply to start the server earlier and hope it starts in time, but starting too early will cause other problems. A short delay will be necessary, but it will only occur if your system is already lagging behind in processing the queue of request. Hopefully should otherwise be unnoticeable. Can test in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8%2Bbeta.4

I think playing with the following settings may help with sound getting lost when playback starts:
`Kodi > Settings > System > Display > Delay after change of refresh rate`
`Kodi > Settings > System > Audio > Keep audio device alive`
`Kodi > Settings > System > Audio > Send low volume noise`

@XxAcielxX - the change that caused this was made in v7.0.8+beta.1 and the whole point of using the beta versions is for testing.

If you don't want things to change or break unexpectedly then don't use the beta versions. No one is forcing you to do testing and if it is too annoying then you can simply stop.

The only other option is that development will be tied to how much time is available for testing (which for me is none) and you may be waiting a very long time for any new versions to use.

**Comment by kuraikaze** [comment]
@MoojMidge
Been testing Beta 4 this morning on about a dozen videos, with various start/stop timings.
No instances of failed playback.
Thank you 👍 

Re: Lost audio - thanks for the suggestions ... but all stuff I've set already.  This Kodi install has been an "upgrade-in-place" setup for *YEARS* on a bunch of iterations of upgraded hardware/platforms, so there's highly likely to be a hell of a lot of old cruft and jank from old versions of things and past sketchy workarounds and legacy `fixes` and settings.  Time for a thorough cleanup/clean-reinstall I think ;)

**Comment by XxAcielxX** [comment]
**7.0.8+beta.4**
Same result here, testing since, and not a single video failed. Videos loading time has reduced to ~15secs as well. Can we further lower the loading time like before, i.e., ~5secs?

Just for the info:
I don't have this lost audio issue as faced by @kuraikaze, even when I have, `Keep audio device alive > Off`, and `Send low volume noise > unticked`.

**Comment by MoojMidge** [comment]
> Videos loading time has reduced to ~15secs as well. Can we further lower the loading time like before, i.e., ~5secs?

It shouldn't even take 5 seconds, but nothing can be done if you don't provide a debug log

**Comment by XxAcielxX** [comment]
> but nothing can be done if you don't provide a debug log

~Here it is: https://pastebin.com/mbBKTRmc~

After cancelling the subtitles selection, to took like 17-20secs for the video to actually play on the screen.

Line 1572
`2024-06-22 12:06:32.890 T:1338    debug <general>: [plugin.video.youtube] Subtitle selection cancelled`

**Comment by MoojMidge** [comment]
@XxAcielxX - that link is not publicly accessible

**Comment by XxAcielxX** [comment]
> @XxAcielxX - that link is not publicly accessible

It's stuck with 'Pending moderation'. Here is another link: https://dpaste.com/AZYHD7GT2

**Comment by MoojMidge** [comment]
Your system gets hit by 66 JSON-RPC requests within a span of 30s after you try to play a video.

No idea what is creating all those requests (you can try to enable the JSON-RPC component logging to get more information), but the request to start the http server simply has to wait for all of those to be processed first.

I can try and jump the queue a bit, but I would suggest you should try to figure out what is happening on your system, as it seems excessive.

**Comment by XxAcielxX** [comment]
> but I would suggest you should try to figure out what is happening on your system

JSON-RPC requests from client `192.168.1.5` = my mobile phone I use to share YT videos, and control LibreELEC using the Yatse (Android App).

I'm using it since last 7 years, it didn't cause the issue before.

**Comment by MoojMidge** [comment]
🤷 If you think that is normal then ok.

If they are all manual control actions then my only further suggestion to you is that you minimise the things you are doing after selecting a video to play if you are unhappy with how long your system takes to process those actions.

Edit:

> I'm using it since last 7 years, it didn't cause the issue before.

Note that more than 40 requests occur after you cancel the subtitle selection, and the plugin is executing code that should complete in a few milliseconds on pretty much any system. If this was taking 5s previously then something is really wrong.

The only difference now is that the plugin is not only getting stuck waiting that 5s, but is also having to wait for all those other requests to be processed, because it now has its own request to make.

For a further idea of how wrong whatever is happening with your system actually is, the device that kuraikaze uses is roughly 2-5x faster than your device in pure CPU workloads. It completes [this small section of code](https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/yt_play.py#L106-L160) (plus a little bit more) in roughly 0.022 seconds (22 milliseconds).

Your device completes almost the exact same thing in 12.3 seconds, which is 559 times slower, while trying to process 25 other JSON-RPC requests.

**Comment by MoojMidge** [comment]
@XxAcielxX - see if there is any difference between [v7.0.8](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8) and [v7.0.9+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.1)

**Comment by XxAcielxX** [comment]
> @XxAcielxX - see if there is any difference between [v7.0.8](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8) and [v7.0.9+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.1)

Thank you for your support. I think my issue is being caused by some lingering affect from in-place upgrade from LibreELEC 11 to 12. I'm going to do a fresh install, and report back. It might take some time though.

**Comment by MoojMidge** [comment]
@XxAcielxX - there are further improvements to this in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.2

At this stage don't think there is anything else I can do about this, short of keeping the http server running all the time (the way it was done in previous versions) which will re-introduce the issue where the server could not be restarted after certain sleep/power saving modes were activated, and which impacted a number of other people.

So far no one else has reported similar issues to yours though, so if there is no improvement, you may just have to deal with it.
