### ISSUE TITLE
7.0.8+beta.2 - cannot open the "main" addon view

### ISSUE THREAD

**Issue by DoctorVanGogh** [anxdpanic/plugin.video.youtube#803]
### Context

Please provide any relevant information about your setup

* Add-on Version: `7.0.8+beta.2`
* Kodi Version: `20.2`
* Kodi GUI Language: `English`
* Operating System: `FireTV`
* Operating System Language: `English`

-----
### Expected Behavior

Going "Add-Ons -> YouTube" *should* open the "Sign In/Subscriptions/My Recommendations/etc." list subpage.

------

### Current Behavior

Going "Add-Ons -> YouTube" does not open a page, but displays an error message.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Open the "Add-Ons" page in Kodi
2.  Select "Youtube"
3. => Error

------

### Log
```
...
2024-06-18 20:55:25.333 T:17116    info <general>: [plugin.video.youtube] Running: YouTube (7.0.8+beta.2) on Nexus (Kodi-20.2) with Python 3.11.2
                                                   Path: /
                                                   Params: {}
...
2024-06-18 20:55:27.448 T:17116   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 63, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 168, in run
                                                       result, options = provider.navigate(context)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 154, in navigate
                                                       result = method(context, re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 193, in _internal_root
                                                       return self.on_root(context, re_match)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1260, in on_root
                                                       if 'likes' in playlists:
                                                          ^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
2024-06-18 20:55:27.699 T:17115   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2024-06-18 20:55:27.701 T:16763   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
...
```

------

### Additional Information

Funnily enough, that page worked *flawlessly* until I managed to fix an issue (preventing sign in) with my API credentials. As soon as the credentials were correct, the page could not be displayed any more.

Another fun fact: I have the *My Subscriptions* element from that list favorited. Going Favorites -> My Subscriptions (bypassing that list) works perfectly fine. Videos are displayed and playable. :rofl:

Small additional tidbit to the error (and the fact that it only occurs with a correctly signed in & authorized account): The google account used does **not** have a youtube channel linked. So I'm guessing the `NoneType` maps to that "lack" of youtube account.

I have vague memories of similar issues with accounts without a channel before.

------

**Comment by MoojMidge** [comment]
Should be fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8%2Bbeta.3
