### ISSUE TITLE
Can't install v7.0.9+beta.1.unofficial.1

### ISSUE THREAD

**Issue by AlexNk** [anxdpanic/plugin.video.youtube#828]
### Context

* Add-on Version: v7.0.9+beta.1.unofficial.1
* Kodi Version: 20.3.0
* Kodi GUI Language: English
* Operating System: Linux x86 (LibreElec)
* Operating System Language: English

### Current Behavior

Updating from zip archive, getting error.

### Log

```
2024-06-28 00:16:08.739 T:778     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'content' from 'youtube_plugin.kodion.constants' (/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/constants/__init__.py)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/service.py", line 13, in <module>
                                                       from youtube_plugin.kodion import service_runner
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/service_runner.py", line 20, in <module>
                                                       from .context import XbmcContext
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/context/__init__.py", line 12, in <module>
                                                       from .xbmc.xbmc_context import XbmcContext
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/context/xbmc/xbmc_context.py", line 37, in <module>
                                                       from ...ui import XbmcContextUI
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/ui/__init__.py", line 12, in <module>
                                                       from .xbmc.xbmc_context_ui import XbmcContextUI
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/ui/xbmc/xbmc_context_ui.py", line 13, in <module>
                                                       from .view_manager import ViewManager
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/ui/xbmc/view_manager.py", line 14, in <module>
                                                       from ...constants import content
                                                   ImportError: cannot import name 'content' from 'youtube_plugin.kodion.constants' (/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/constants/__init__.py)
                                                   -->End of Python script error report<--
```

**Comment by MoojMidge** [comment]
Yep the original release is broken.

Already fixed, but don't intend to create a new release just for this. Will just have to wait until the next (beta) release, or you can download directly from current nexus-unofficial head: https://github.com/anxdpanic/plugin.video.youtube/archive/refs/heads/nexus-unofficial.zip

**Comment by MoojMidge** [comment]
New beta is available. Unofficial releases should work again

https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.2
