### ISSUE TITLE
ERROR: EXCEPTION Thrown (PythonToCppException)

### ISSUE THREAD

**Issue by LukaszFormela** [anxdpanic/plugin.video.youtube#91]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.9
* Kodi Version: 18.7
* Kodi GUI Language: English
* Operating System: Raspbian
* Operating System Language: English

------

### Expected Behavior

Search results should play videos

------

### Current Behavior

99% of videos can't be played, generic on-screen error is thrown by Kodi. More details in kodi.log

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to "Add Ons"
2. Enter "Video add-ons" > "YouTube"
3. Search for any video
4. Try to open any video from successfull search results.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

```
2021-02-13 14:04:59.911 T:1436004576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1024, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 986, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
```

------

### Additional Information

1 in 100 videos still can be played. I have recreated API keys in the first place, but it made no difference.
`apt-get update` and `apt-get upgrade` made some updates, but that didn't resolve the issue.

------

**Comment by resende1776** [comment]
Same problem here, running on a Ubuntu Xenial, Kodi 18.9

**Comment by anxdpanic** [comment]
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
