### ISSUE TITLE
7.1.0 crashes on Xbox

### ISSUE THREAD

**Issue by tpaniaki** [anxdpanic/plugin.video.youtube#923]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.0
* Kodi Version: 21.1
* Kodi GUI Language: French
* Operating System: Xbox
* Operating System Language: French

------

### Expected Behavior

Addon starts without errors.

------

### Current Behavior

Addon crashes at boot.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install 7.1.0 on Xbox.
2. Witness the crash.

------

### Log

[debug log](https://paste.kodi.tv/foluyemexe).

Perhaps this?

```
2024-10-07 19:35:21.071 T:3760    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
                                                   Traceback (most recent call last):
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\service.py", line 13, in <module>
                                                       from youtube_plugin.kodion import service_runner
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\service_runner.py", line 23, in <module>
                                                       from ..youtube.provider import Provider
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\__init__.py", line 13, in <module>
                                                       from .provider import Provider
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 19, in <module>
                                                       from .client import APICheck, YouTube
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\__init__.py", line 14, in <module>
                                                       from .youtube import YouTube
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 21, in <module>
                                                       from ..helper.stream_info import StreamInfo
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\__init__.py", line 15, in <module>
                                                       from .url_to_item_converter import UrlToItemConverter
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\url_to_item_converter.py", line 15, in <module>
                                                       from . import utils
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\utils.py", line 27, in <module>
                                                       from inputstreamhelper import Helper as ISHelper
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 14, in <module>
                                                       from .widevine.arm import dl_extract_widevine_chromeos, extract_widevine_chromeos, install_widevine_arm
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.inputstreamhelper\lib\inputstreamhelper\widevine\arm.py", line 13, in <module>
                                                       from .arm_lacros import cdm_from_lacros, install_widevine_arm_lacros
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.inputstreamhelper\lib\inputstreamhelper\widevine\arm_lacros.py", line 7, in <module>
                                                       from ctypes.util import find_library
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 468, in <module>
                                                       GetLastError = windll.kernel32.GetLastError
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 443, in __getattr__
                                                       dll = self._dlltype(name)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 373, in __init__
                                                       self._handle = _dlopen(self._name, mode)
                                                   FileNotFoundError: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
                                                   -->End of Python script error report<--
                                                   
2024-10-07 19:35:21.072 T:3760    debug <general>: CPythonInvoker::onExecutionDone(7, Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\service.py)
```

------

### Additional Information

Was also happening in the previous version.

------

**Comment by MoojMidge** [comment]
This is an issue in InputStream Helper, or more broadly an issue with the way Kodi initialises system paths for Python on the Xbox platform

Will workaround the issue in this plugin, by not loading InputStream Helper unless it is actually needed, but suggest raising a bug report here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues
