### ISSUE TITLE
Invalid URL u'http://': No host supplied

### ISSUE THREAD

**Issue by springjools** [anxdpanic/plugin.video.youtube#94]
### Context

Please provide any relevant information about your setup

* Add-on Version: plugin.video.youtube v6.8.9 installed
* Kodi Version: Kodi (18.7 Git:20200528-2c5354e70a). Platform: Linux ARM 32-bit
* Kodi GUI Language: en
* Operating System: Linux jovian 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
* Operating System Language: en

------

### Expected Behavior
Plugin works

------

### Current Behavior
Plugin doesn't work. Report youtube plugin error.

Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1024, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 986, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to play a video
 
 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://privatebin.net/?caab4f4125d50233#87yRWQRESzBD79QG3amPFaHCf996MvX9hBsQpYDdKBxm

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by anxdpanic** [comment]
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
