### ISSUE TITLE
Links sent via uri2addon fail to play

### ISSUE THREAD

**Issue by benyamin-codez** [anxdpanic/plugin.video.youtube#946]
### Context

* Add-on Version: 7.1.1+beta.2
* Kodi Version: 20.5
* Kodi GUI Language: English
* Operating System: 5.15.92-1-osmc
* Operating System Language: English

------

### Fault

Playing a YT video via uri2addon, e.g. using Yatse, results in an error.

------

### Log

Snippet only:

```
 info <general>: [plugin.video.youtube] Plugin: Running |v7.1.1+beta.2|
                  Kodi: |v20.5 (Kodi Unknown release)|
                  Python: |v3.9.2|
                  Path: |/uri2addon/|
                  Params: |{'uri': 'https://youtube.com/watch?v=yRwS6T6HUME&si=VD__JJTBf6EB1YPT'}|
debug <general>: ------ Window Deinit (DialogBusy.xml) ------
debug <general>: Thread ScriptObs 1256542464 terminating
error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/uri2addon/?uri=https%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3DyRwS6T6HUME%26si%3DVD__JJTBf6EB1YPT]
...
 info <general>: [plugin.video.youtube] Converting VideoItem |plugin://plugin.video.youtube/play/?video_id=yRwS6T6HUME|
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                  Error Type: <class 'TypeError'>
                  Error Contents: not a valid non-string sequence or mapping object
                  Traceback (most recent call last):
                      File "/usr/lib/python3.9/urllib/parse.py", line 928, in urlencode
                      if len(query) and not isinstance(query[0], tuple):
                  TypeError: object of type 'NoneType' has no len()
                  
                  During handling of the above exception, another exception occurred:
                  
                  Traceback (most recent call last):
                      File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                      plugin_runner.run()
                      File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 67, in run
                      plugin.run(provider, context, focused=(current_uri == new_uri))
                      File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 214, in run
                      item = self._PLAY_ITEM_MAP[result.__class__.__name__](
                      File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 485, in playback_item
                      headers = media_item.get_headers(as_string=True)
                      File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/media_item.py", line 223, in get_headers
                      return urlencode(self._headers)
                      File "/usr/lib/python3.9/urllib/parse.py", line 936, in urlencode
                      raise TypeError("not a valid non-string sequence "
                      File "/usr/lib/python3.9/urllib/parse.py", line 928, in urlencode
                      if len(query) and not isinstance(query[0], tuple):
                  TypeError: not a valid non-string sequence or mapping object
                  -->End of Python script error report<--
```
------

### Additional Information

Began after upgrade to v7.1.1+beta.2

------

**Comment by MoojMidge** [comment]
Should be fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.3
