### ISSUE TITLE
Kodi-19 unplayable channel

### ISSUE THREAD

**Issue by anrxc** [anxdpanic/plugin.video.youtube#96]
### Context

I used to watch some videos on this channel as recently as Kodi-19-beta. But now the videos will not play. 

Interestingly new videos show up in "My Subscriptions" but if you try to visit the channel page it will not load a list of those same videos that are appearing sucesfully in "My Subscriptions". 

I suspected it could be another encoding issue, since the channel uses what I'm guessing is either cp1250 or 8859-2 characters in every video title. But the trace is more generic than that.

* Add-on Version: 6.8.9+matrix.1
* Kodi Version: 19
* Kodi GUI Language: English/US
* Operating System: Windows 10
* Operating System Language: English/US

------

### Expected Behavior

Public video starts playing.

------

### Current Behavior

Video that is public does not play.

------

### Steps to Reproduce

Try to play for example this video in Kodi: https://www.youtube.com/watch?v=fLc9hMQt5A0

------

### Log

2021-02-21 15:44:26.570 T:5800     INFO <general>: initializing python engine.
2021-02-21 15:44:26.571 T:5800     INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.9+matrix.1) on Matrix (Kodi-19.0) with Python 3.8.5
                                                   	Path: /play/
                                                   	Params: {'video_id': 'fLc9hMQt5A0'}
2021-02-21 15:44:27.715 T:5800    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.InvalidURL'>
                                                   Error Contents: Invalid URL 'http://': No host supplied
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py", line 15, in <module>
                                                       runner.run(__provider__)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\runner.py", line 60, in run
                                                       __RUNNER__.run(provider, context)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_runner.py", line 33, in run
                                                       results = provider.navigate(context)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 105, in navigate
                                                       result = method(context, re_match)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\register_provider_path.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 767, in on_play
                                                       return yt_play.play_video(self, context)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 104, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 515, in load_stream_infos
                                                       return self._method_get_video_info(video_id)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 1024, in _method_get_video_info
                                                       parse_to_stream_list(std_fmts)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 986, in parse_to_stream_list
                                                       url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\signature\cipher.py", line 32, in get_signature
                                                       json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\function_cache.py", line 108, in get
                                                       cached_data = partial_func()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\signature\cipher.py", line 52, in _load_json_script
                                                       result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 75, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 60, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 519, in request
                                                       prep = self.prepare_request(req)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 452, in prepare_request
                                                       p.prepare(
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 313, in prepare
                                                       self.prepare_url(url, params)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 390, in prepare_url
                                                       raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                                   requests.exceptions.InvalidURL: Invalid URL 'http://': No host supplied
                                                   -->End of Python script error report<--
                                                   
2021-02-21 15:44:27.753 T:5800     INFO <general>: Python interpreter stopped
2021-02-21 15:44:27.776 T:9752    ERROR <general>: Skipped 2 duplicate messages..
2021-02-21 15:44:27.776 T:9752    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=fLc9hMQt5A0]

------

**Comment by anxdpanic** [comment]
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
