### ISSUE TITLE
Addon 7.1.1beta7 on LibreElec-RPi4 error "invalid client" on login

### ISSUE THREAD

**Issue by phpTrix** [anxdpanic/plugin.video.youtube#976]
### Context

* Add-on Version: 7.1.1beta7
* Kodi Version: 21.1 on RPi4 LibreElec
* Kodi GUI Language: DE
* Operating System: LibreElec
* Operating System Language: EN

------

### Expected Behavior

Youtube login should work, videos should play

------

### Current Behavior

Error-Box 
LoginException: {'error': 'invalid_client', 'error_description': 'Unauthorized', 'code': 401}
No video playback (please log in).

------

### Steps to Reproduce

1.  Try to login

------

### Log

2024-11-14 20:43:12.325 T:3348     info <general>: [plugin.video.youtube] Plugin: Running v7.1.1+beta.7.unofficial.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.11.9
                                                        Path:   |/sign/in/|
                                                        Params: |{'category_label': 'Anmelden'}|
2024-11-14 20:43:14.030 T:3348    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                        Access token request - Failed
                                                        Exception: LoginException('"error" in response JSON data')
                                                        Client:    |
                                                        config_type:   |YouTube-Kodi|
                                                        client_id:     |296...t.com|
                                                        client_secret: |GOC...dtX||
                                                        Response:   {'error': 'invalid_client', 'error_description': 'Unauthorized', 'code': 401}
2024-11-14 20:43:14.033 T:3348    error <general>: [plugin.video.youtube] LoginException: {'error': 'invalid_client', 'error_description': 'Unauthorized', 'code': 401}
2024-11-14 20:43:14.036 T:3348    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 67, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 273, in run
                                                       try_fallback = options.get(provider.RESULT_TRY_FALLBACK, True)
                                                                      ^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--

------

### Additional Information

I created new API-Key and Client-Key as recommended. No change.

------

**Comment by MoojMidge** [comment]
> I created new API-Key and Client-Key as recommended. No change.

Try again. The error means that you haven't done this correctly.

You can refer to the instructions here:
https://github.com/anxdpanic/plugin.video.youtube/issues/439#issuecomment-1509319017

Pay particular attention to Step 10.
