### ISSUE TITLE
Uncaught Exception during Sign In

### ISSUE THREAD

**Issue by yggdr** [anxdpanic/plugin.video.youtube#985]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.1
* Kodi Version: 21.1
* Kodi GUI Language: en
* Operating System: OSMC 2024.10-1 (Debian 11)
* Operating System Language: en

In #979 I mentioned that some days ago video playback stopped working with some strange permission error. So I tried following that advice by redoing the API-Key/OAUTH-Dance on google, and for that I installed the just released 7.1.1.1, erased the old API-KEY/OAUTH-IDs etc, and executed "Delete api_keys.json" from the settings menu. Then, when I tried to login again and after getting the info screen about the two login keys, it throws me back to the Menu with a generic "youtube error".

In the logs I found an uncaught `ValueError`.

------

### Expected Behavior

Being able to log in.

------

### Current Behavior

What is the current behavior?

Uncaught `ValueError`

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have API Keys/OAUTHID unset in settings
2. Install 7.1.1.1
3. Select "Sign In"

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

```
2024-11-18 17:16:55.437 T:26979    info <general>: CAddonMgr::FindAddon: plugin.video.youtube v7.1.1.1 installed
2024-11-18 17:16:55.806 T:21785 warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-11-18 17:17:04.091 T:27004    info <general>: [plugin.video.youtube] Service: Starting v7.1.1.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.9.2
2024-11-18 17:17:12.362 T:27017    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.9.2
                                                        Path:   |/|
                                                        Params: |{}|
2024-11-18 17:17:14.906 T:27017    info <general>: Skipped 1 duplicate messages..
2024-11-18 17:17:14.906 T:27017    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.9.2
                                                        Path:   |/sign/in/|
                                                        Params: |{'category_label': 'Sign In'}|
2024-11-18 17:17:16.352 T:27017   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: min() arg is an empty sequence
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in module>
                                                       plugin_runner.run()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 67, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 185, in run
                                                       result, options = provider.navigate(context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 169, in navigate
                                                       result = handler(provider=self, context=context, re_match=re_match)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 769, in on_sign
                                                       yt_login.process(mode, provider, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_login.py", line 138, in process
                                                       access_manager.update_access_token(addon_id, *zip(*tokens))
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/access_manager.py", line 460, in update_access_token
                                                       min(map(int, [val for val in expiry if val]))
                                                   ValueError: min() arg is an empty sequence
                                                   -->End of Python script error report<--
```

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Thanks for picking that up.

Fix will be available in next beta, or you can apply the changes yourself if you are able to from here: https://github.com/MoojMidge/plugin.video.youtube/commit/f8ec610f9bd1851bd278c1cb855aebbf8038f4cd

I think this error should only occur if the sign-in fails. Were you able to eventually sign-in successfully?

**Comment by yggdr** [comment]
Yes, after manual patching, and then solving the slight problem of me not being able to read the instructions properly, I was just now able to login and play videos again, thank you very much :)

**Comment by MoojMidge** [comment]
Great. Thanks for confirming.
